# Иванов Матвей - подгруппа 1

### подготовка

In [62]:
# подключили библиотеку
import sqlite3
import pandas as pd

In [63]:
def print_table(fetchall):
    for row in fetchall:
        print(row)

In [64]:
# настроили соединение и способ взаимодействия
connection = sqlite3.connect('ivanov_lab01.db')
cursor = connection.cursor()

In [65]:
# загрузили данные в нашу БД
cursor.executescript(open("ai_data_lab.sql").read())
connection.commit()

In [66]:
# проверили БД
query = '''
SELECT COUNT(*) AS rows_in_lab
FROM run_overview;
'''
pd.read_sql_query(query, connection)

   rows_in_lab
0          160

### пара 1

##### задание 1

In [67]:
query = '''
SELECT *
FROM run_overview
LIMIT 10;
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,1,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,RTX 4090,2026-08-31 15:51:00,38,0.00300,64,0.8618,0.8688,debug
1,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
2,3,3,tabular_class_weight_003,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Fraud Mini,internal,125000,completed,RTX 4090,2026-09-13 23:14:00,191,0.00010,128,0.8547,0.8013,full_train
3,4,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,T4,2026-09-04 08:19:00,127,0.00030,64,0.8055,0.8287,full_train
4,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
5,6,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,failed,T4,2026-09-04 21:23:00,17,0.00010,32,0.6171,NaN,production_candidate
6,7,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-28 09:10:00,195,0.00100,32,0.9198,0.8749,debug
7,8,8,cv_tuned_008,Дарья Новикова,CV,ResNet50,ResNet,CV,CIFAR-10,public,60000,completed,CPU,2026-09-01 11:02:00,165,0.00005,32,0.7537,0.7308,class_weight
8,9,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,CPU,2026-09-01 09:38:00,66,0.01000,32,0.8899,0.9042,fast_test
9,10,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-09-18 07:21:00,225,0.00010,64,0.5504,NaN,augmentation

##### задание 2

In [68]:
query = '''
SELECT run_id, model_name, dataset_name, task_type, status
FROM run_overview;
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

     run_id        model_name     dataset_name task_type     status
0         1        DistilBERT      RuSentiment       NLP  completed
1         2     ConvNeXt-Tiny     Cats vs Dogs        CV  completed
2         3      RandomForest       Fraud Mini   Tabular  completed
3         4       MobileNetV3     Cats vs Dogs        CV  completed
4         5          LightGBM   Customer Churn   Tabular  completed
..      ...               ...              ...       ...        ...
155     156      RandomForest   Customer Churn   Tabular     failed
156     157  DeBERTa-v3-small      RuSentiment       NLP    running
157     158          ResNet50     PlantVillage        CV  completed
158     159      RandomForest  Student Success   Tabular    running
159     160         BERT-base          AG News       NLP  completed

[160 rows x 5 columns]

##### задание 3

In [69]:
query = '''
SELECT DISTINCT task_type
FROM run_overview;
'''
pd.read_sql_query(query, connection)

  task_type
0       NLP
1        CV
2   Tabular

##### задание 4

In [70]:
query = '''
SELECT DISTINCT dataset_source
FROM run_overview;
'''
pd.read_sql_query(query, connection)

  dataset_source
0       internal
1         public

##### задание 5

In [71]:
query = '''
SELECT *
FROM run_overview
WHERE status = 'completed';
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,1,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,RTX 4090,2026-08-31 15:51:00,38,0.00300,64,0.8618,0.8688,debug
1,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
2,3,3,tabular_class_weight_003,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Fraud Mini,internal,125000,completed,RTX 4090,2026-09-13 23:14:00,191,0.00010,128,0.8547,0.8013,full_train
3,4,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,T4,2026-09-04 08:19:00,127,0.00030,64,0.8055,0.8287,full_train
4,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,151,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,RTX 4090,2026-08-27 10:24:00,23,0.00005,16,0.9255,0.8660,full_train
103,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
104,154,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,T4,2026-09-14 19:46:00,268,0.00010,16,0.7997,0.7474,class_weight
105,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
106,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

##### задание 6

In [72]:
query = '''
SELECT *
FROM run_overview
WHERE f1_score >= 0.85;
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,1,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,RTX 4090,2026-08-31 15:51:00,38,0.00300,64,0.8618,0.8688,debug
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,7,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-28 09:10:00,195,0.00100,32,0.9198,0.8749,debug
3,9,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,CPU,2026-09-01 09:38:00,66,0.01000,32,0.8899,0.9042,fast_test
4,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
5,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
6,14,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,L40S,2026-09-17 17:04:00,233,0.00010,16,0.8477,0.8500,debug
7,16,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,T4,2026-08-30 09:12:00,184,0.00100,64,0.9850,0.9800,full_train
8,18,18,cv_new_features_018,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,RTX 4090,2026-08-24 14:27:00,69,0.01000,64,0.8670,0.8915,tuned
9,20,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,CPU,2026-09-28 09:32:00,241,0.01000,64,0.9340,0.8968,production_candidate
10,22,22,nlp_class_weight_022,Иван Ким,NLP,DeBERTa-v3-small,DeBERTa,NLP,RuSentiment,internal,31000,completed,T4,2026-09-18 18:51:00,130,0.00010,16,0.9291,0.9301,tuned
11,24,24,tabular_tuned_024,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Student Success,internal,18000,completed,L40S,2026-08-29 16:19:00,264,0.00030,128,0.8810,0.8698,baseline
12,27,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,RTX 4090,2026-08-29 15:47:00,135,0.00300,32,0.9226,0.8859,production_candidate
13,28,28,cv_lr_sweep_028,Алексей Пак,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,T4,2026-09-09 07:55:00,276,0.00030,64,0.9403,0.9514,full_train
14,39,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,T4,2026-09-23 17:21:00,149,0.01000,32,0.8938,0.9127,fast_test
15,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate
16,51,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,completed,T4,2026-09-04 16:37:00,228,0.00030,64,0.9587,0.9498,class_weight
17,52,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,A100,2026-08-30 03:36:00,257,0.00100,32,0.8795,0.8905,production_candidate
18,57,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,CPU,2026-08-23 05:08:00,9,0.00010,128,0.8668,0.8610,production_candidate
19,58,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,RTX 4090,2026-09-18 11:48:00,73,0.00300,64,0.9412,0.9510,tuned
20,59,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,T4,2026-09-19 16:06:00,199,0.00010,32,0.9850,0.9695,fast_test
21,60,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-08-28 09:45:00,66,0.01000,16,0.8903,0.8975,production_candidate
22,61,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-29 18:01:00,174,0.00010,16,0.9750,0.9697,class_weight
23,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
24,66,21,tabular_tuned_021,Даниил Ли,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,T4,2026-09-16 10:11:00,249,0.00100,64,0.9254,0.9113,production_candidate
25,70,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,L40S,2026-09-21 17:48:00,127,0.00100,16,0.9452,0.8863,class_weight
26,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
27,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
28,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
29,79,34,nlp_sanity_check_034,Максим Чернов,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,L40S,2026-09-03 08:28:00,112,0.00030,16,0.9388,0.8891,augmentation
30,84,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,L40S,2026-09-20 21:58:00,234,0.01000,64,0.8972,0.9012,baseline
31,93,3,tabular_class_weight_003,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Fraud Mini,internal,125000,completed,T4,2026-09-10 20:48:00,213,0.00100,16,0.9024,0.8694,full_train
32,95,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 10:21:00,224,0.00030,16,0.8767,0.8807,full_train
33,96,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,completed,T4,2026-09-07 14:48:00,119,0.01000,128,0.8801,0.8857,baseline
34,100,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,completed,L40S,2026-09-17 18:05:00,38,0.00300,32,0.8901,0.8604,baseline
35,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
36,105,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,L40S,2026-08-27 21:43:00,180,0.00030,64,0.9503,0.9256,augmentation
37,114,24,tabular_tuned_024,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Student Success,internal,18000,completed,T4,2026-08-27 10:11:00,167,0.00005,16,0.9290,0.8854,debug
38,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
39,126,36,tabular_sanity_check_036,Мария Орлова,Tabular,LogisticRegression,Linear,Tabular,Fraud Mini,internal,125000,completed,T4,2026-09-25 02:51:00,162,0.00100,128,0.9637,0.9614,debug
40,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
41,131,41,tabular_lr_sweep_041,Полина Кравцова,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,RTX 4090,2026-09-14 04:34:00,189,0.00300,64,0.8516,0.8672,full_train
42,134,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-15 21:08:00,148,0.01000,32,0.8723,0.8665,tuned
43,142,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-29 02:37:00,271,0.00010,32,0.9415,0.8897,debug
44,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
45,146,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,completed,L40S,2026-08-28 22:11:00,238,0.00010,16,0.9590,0.9475,debug
46,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
47,149,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-16 12:07:00,154,0.00100,128,0.8619,0.8500,tuned
48,151,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,RTX 4090,2026-08-27 10:24:00,23,0.00005,16,0.9255,0.8660,full_train
49,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
50,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
51,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

##### задание 7

In [73]:
query = '''
SELECT *
FROM run_overview
WHERE gpu IN ('A100', 'H100');
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,10,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-09-18 07:21:00,225,0.00010,64,0.5504,NaN,augmentation
3,11,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-08-28 01:44:00,199,0.00005,64,NaN,NaN,baseline
4,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,156,21,tabular_tuned_021,Даниил Ли,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,failed,A100,2026-09-14 13:14:00,234,0.00010,128,NaN,NaN,tuned
66,157,22,nlp_class_weight_022,Иван Ким,NLP,DeBERTa-v3-small,DeBERTa,NLP,RuSentiment,internal,31000,running,A100,2026-09-18 12:31:00,133,0.00030,64,NaN,NaN,production_candidate
67,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
68,159,24,tabular_tuned_024,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Student Success,internal,18000,running,A100,2026-08-27 12:57:00,248,0.00100,32,NaN,NaN,baseline
69,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

##### задание 8

In [75]:
query = '''
SELECT *
FROM run_overview
WHERE status = 'completed'
ORDER BY f1_score DESC
LIMIT 5;
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,16,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,T4,2026-08-30 09:12:00,184,0.0010,64,0.9850,0.9800,full_train
1,61,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-29 18:01:00,174,0.0001,16,0.9750,0.9697,class_weight
2,59,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,T4,2026-09-19 16:06:00,199,0.0001,32,0.9850,0.9695,fast_test
3,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.0001,32,0.9721,0.9654,production_candidate
4,126,36,tabular_sanity_check_036,Мария Орлова,Tabular,LogisticRegression,Linear,Tabular,Fraud Mini,internal,125000,completed,T4,2026-09-25 02:51:00,162,0.0010,128,0.9637,0.9614,debug

##### задание 9

In [76]:
query = '''
SELECT model_name, accuracy, accuracy * 100 AS accuracy_percent
FROM run_overview;
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

           model_name  accuracy  accuracy_percent
0          DistilBERT    0.8618             86.18
1       ConvNeXt-Tiny    0.7634             76.34
2        RandomForest    0.8547             85.47
3         MobileNetV3    0.8055             80.55
4            LightGBM    0.9473             94.73
..                ...       ...               ...
155      RandomForest       NaN               NaN
156  DeBERTa-v3-small       NaN               NaN
157          ResNet50    0.9058             90.58
158      RandomForest       NaN               NaN
159         BERT-base    0.9721             97.21

[160 rows x 3 columns]

##### задание 10

In [ ]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    gpu IN ('A100', 'H100')
    AND
    accuracy >= 0.90
ORDER BY accuracy DESC;
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate
1,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
2,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
3,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
4,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
5,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
6,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
7,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
8,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
9,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
10,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
11,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
12,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
13,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate

### Expert Track 1

##### EXPERT A

задание: Проверьте утверждение: «Если используют H100 то результат всегда высокий». Найдите завершённые эксперименты на H100-запуски где f1_score < 0.75. Если строки есть — сформулируйте, подтверждается ли утверждение или опровергается. \
ответ: утверждение опровергается, так как есть завершённые запуски на H100 с f1_score < 0.75, значит GPU H100 не гарантирует высокий результат

In [79]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    gpu = 'H100'
    AND
    f1_score < 0.75
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,78,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,H100,2026-09-15 15:20:00,231,0.0030,32,0.7480,0.7120,debug
1,109,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-12 02:39:00,125,0.0003,128,0.7893,0.7389,debug

##### EXPERT B

задание: Найдите ошибку в логике запроса ниже. Руководитель считает, что он возвращает только завершённые запуски на A100 и H100. Проверьте это и исправьте. \
SELECT * \
FROM run_overview \
WHERE status = 'completed' \
  AND gpu = 'A100' \
   OR gpu = 'H100'; \
ответ: при таком запросе у нас либо завершённое на A100, либо на H100 (без упоминания завершённости)

In [80]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    gpu = 'A100'
    OR
    gpu = 'H100'

'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,10,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-09-18 07:21:00,225,0.00010,64,0.5504,NaN,augmentation
3,11,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-08-28 01:44:00,199,0.00005,64,NaN,NaN,baseline
4,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
5,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
6,17,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-04 08:35:00,59,0.01000,128,0.7296,0.7422,class_weight
7,23,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,cancelled,H100,2026-09-06 06:09:00,108,0.00300,64,NaN,NaN,augmentation
8,25,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 11:00:00,198,0.00100,64,0.7210,0.6940,baseline
9,26,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 22:02:00,189,0.00010,32,0.8745,0.8376,augmentation
10,32,32,cv_baseline_032,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,H100,2026-09-07 09:47:00,127,0.00005,16,0.8400,0.8091,augmentation
11,33,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,A100,2026-09-14 10:14:00,60,0.00005,32,0.8462,0.8282,full_train
12,34,34,nlp_sanity_check_034,Максим Чернов,NLP,BERT-base,BERT,NLP,AG News,public,120000,failed,H100,2026-09-03 13:27:00,187,0.00030,16,NaN,NaN,production_candidate
13,35,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 07:48:00,204,0.00100,32,0.8785,0.8335,production_candidate
14,38,38,tabular_baseline_038,Даниил Ли,Tabular,LightGBM,Gradient Boosting,Tabular,Credit Default,public,30000,completed,H100,2026-09-22 05:30:00,97,0.00005,16,0.8609,0.8400,fast_test
15,40,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 20:26:00,40,0.01000,128,0.8067,0.7747,augmentation
16,43,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-08-24 07:34:00,208,0.00010,64,0.8797,0.8213,class_weight
17,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate
18,47,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-02 16:34:00,10,0.00100,128,0.7452,0.7328,class_weight
19,49,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-04 03:34:00,72,0.00100,128,0.6711,0.6258,debug
20,50,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 07:04:00,50,0.00300,16,0.8237,0.7683,debug
21,52,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,A100,2026-08-30 03:36:00,257,0.00100,32,0.8795,0.8905,production_candidate
22,60,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-08-28 09:45:00,66,0.01000,16,0.8903,0.8975,production_candidate
23,64,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,failed,H100,2026-09-14 05:17:00,94,0.00030,32,NaN,NaN,production_candidate
24,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
25,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
26,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
27,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
28,78,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,H100,2026-09-15 15:20:00,231,0.00300,32,0.7480,0.7120,debug
29,80,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-09 21:42:00,137,0.01000,128,0.8894,0.8389,production_candidate
30,85,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 18:09:00,122,0.00300,128,0.7967,0.7627,debug
31,95,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 10:21:00,224,0.00030,16,0.8767,0.8807,full_train
32,97,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,H100,2026-08-28 23:44:00,96,0.01000,32,0.8206,0.8271,augmentation
33,99,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-31 05:50:00,44,0.00010,128,0.8259,0.7769,full_train
34,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
35,104,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-17 12:27:00,198,0.00010,16,0.8879,0.8348,tuned
36,109,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-12 02:39:00,125,0.00030,128,0.7893,0.7389,debug
37,115,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,cancelled,H100,2026-09-25 06:37:00,88,0.00100,64,NaN,NaN,tuned
38,117,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,running,H100,2026-08-30 03:22:00,77,0.00010,128,0.6632,NaN,production_candidate
39,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
40,120,30,tabular_dropout_030,Никита Фролов,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,A100,2026-09-23 14:33:00,258,0.00300,16,0.8151,0.7922,production_candidate
41,124,34,nlp_sanity_check_034,Максим Чернов,NLP,BERT-base,BERT,NLP,AG News,public,120000,failed,H100,2026-09-06 01:27:00,151,0.00100,16,NaN,NaN,full_train
42,127,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,completed,A100,2026-08-21 05:51:00,194,0.00030,128,0.8636,0.8130,augmentation
43,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
44,133,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,failed,H100,2026-08-25 06:58:00,9,0.00005,64,0.6604,NaN,debug
45,134,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-15 21:08:00,148,0.01000,32,0.8723,0.8665,tuned
46,136,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,A100,2026-08-31 04:10:00,178,0.01000,16,0.8106,0.7812,augmentation
47,137,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-01 10:27:00,78,0.00100,64,0.8903,0.8368,baseline
48,139,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-03 01:42:00,134,0.01000,16,0.7451,0.7006,debug
49,143,8,cv_tuned_008,Дарья Новикова,CV,ResNet50,ResNet,CV,CIFAR-10,public,60000,failed,H100,2026-08-29 13:20:00,73,0.00030,16,0.6308,NaN,tuned
50,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
51,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
52,149,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-16 12:07:00,154,0.00100,128,0.8619,0.8500,tuned
53,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
54,155,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-09-24 09:37:00,28,0.00010,64,NaN,NaN,debug
55,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
56,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

In [85]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    gpu IN ('A100', 'H100');
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
3,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
4,17,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-04 08:35:00,59,0.01000,128,0.7296,0.7422,class_weight
5,25,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 11:00:00,198,0.00100,64,0.7210,0.6940,baseline
6,26,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 22:02:00,189,0.00010,32,0.8745,0.8376,augmentation
7,32,32,cv_baseline_032,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,H100,2026-09-07 09:47:00,127,0.00005,16,0.8400,0.8091,augmentation
8,33,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,A100,2026-09-14 10:14:00,60,0.00005,32,0.8462,0.8282,full_train
9,35,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 07:48:00,204,0.00100,32,0.8785,0.8335,production_candidate
10,38,38,tabular_baseline_038,Даниил Ли,Tabular,LightGBM,Gradient Boosting,Tabular,Credit Default,public,30000,completed,H100,2026-09-22 05:30:00,97,0.00005,16,0.8609,0.8400,fast_test
11,40,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 20:26:00,40,0.01000,128,0.8067,0.7747,augmentation
12,43,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-08-24 07:34:00,208,0.00010,64,0.8797,0.8213,class_weight
13,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate
14,47,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-02 16:34:00,10,0.00100,128,0.7452,0.7328,class_weight
15,49,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-04 03:34:00,72,0.00100,128,0.6711,0.6258,debug
16,50,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 07:04:00,50,0.00300,16,0.8237,0.7683,debug
17,52,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,A100,2026-08-30 03:36:00,257,0.00100,32,0.8795,0.8905,production_candidate
18,60,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-08-28 09:45:00,66,0.01000,16,0.8903,0.8975,production_candidate
19,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
20,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
21,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
22,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
23,78,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,H100,2026-09-15 15:20:00,231,0.00300,32,0.7480,0.7120,debug
24,80,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-09 21:42:00,137,0.01000,128,0.8894,0.8389,production_candidate
25,85,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 18:09:00,122,0.00300,128,0.7967,0.7627,debug
26,95,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 10:21:00,224,0.00030,16,0.8767,0.8807,full_train
27,97,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,H100,2026-08-28 23:44:00,96,0.01000,32,0.8206,0.8271,augmentation
28,99,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-31 05:50:00,44,0.00010,128,0.8259,0.7769,full_train
29,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
30,104,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-17 12:27:00,198,0.00010,16,0.8879,0.8348,tuned
31,109,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-12 02:39:00,125,0.00030,128,0.7893,0.7389,debug
32,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
33,120,30,tabular_dropout_030,Никита Фролов,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,A100,2026-09-23 14:33:00,258,0.00300,16,0.8151,0.7922,production_candidate
34,127,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,completed,A100,2026-08-21 05:51:00,194,0.00030,128,0.8636,0.8130,augmentation
35,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
36,134,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-15 21:08:00,148,0.01000,32,0.8723,0.8665,tuned
37,136,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,A100,2026-08-31 04:10:00,178,0.01000,16,0.8106,0.7812,augmentation
38,137,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-01 10:27:00,78,0.00100,64,0.8903,0.8368,baseline
39,139,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-03 01:42:00,134,0.01000,16,0.7451,0.7006,debug
40,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
41,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
42,149,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-16 12:07:00,154,0.00100,128,0.8619,0.8500,tuned
43,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
44,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
45,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

##### EXPERT C

задание: Если SQL для вас давно знаком: решите Expert B минимум двумя способами и объясните, какой вариант легче читать и поддерживать. \
ответ: третий вариант проще в чтении и поддержке, потому что написан более лаконичнее и используется лишь одна логическая операция, в остальных вариантах с 3-4 операциями легко запустаться

In [82]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    (
        gpu = 'A100'
        OR
        gpu = 'H100'
    )
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
3,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
4,17,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-04 08:35:00,59,0.01000,128,0.7296,0.7422,class_weight
5,25,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 11:00:00,198,0.00100,64,0.7210,0.6940,baseline
6,26,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 22:02:00,189,0.00010,32,0.8745,0.8376,augmentation
7,32,32,cv_baseline_032,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,H100,2026-09-07 09:47:00,127,0.00005,16,0.8400,0.8091,augmentation
8,33,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,A100,2026-09-14 10:14:00,60,0.00005,32,0.8462,0.8282,full_train
9,35,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 07:48:00,204,0.00100,32,0.8785,0.8335,production_candidate
10,38,38,tabular_baseline_038,Даниил Ли,Tabular,LightGBM,Gradient Boosting,Tabular,Credit Default,public,30000,completed,H100,2026-09-22 05:30:00,97,0.00005,16,0.8609,0.8400,fast_test
11,40,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 20:26:00,40,0.01000,128,0.8067,0.7747,augmentation
12,43,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-08-24 07:34:00,208,0.00010,64,0.8797,0.8213,class_weight
13,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate
14,47,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-02 16:34:00,10,0.00100,128,0.7452,0.7328,class_weight
15,49,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-04 03:34:00,72,0.00100,128,0.6711,0.6258,debug
16,50,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 07:04:00,50,0.00300,16,0.8237,0.7683,debug
17,52,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,A100,2026-08-30 03:36:00,257,0.00100,32,0.8795,0.8905,production_candidate
18,60,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-08-28 09:45:00,66,0.01000,16,0.8903,0.8975,production_candidate
19,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
20,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
21,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
22,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
23,78,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,H100,2026-09-15 15:20:00,231,0.00300,32,0.7480,0.7120,debug
24,80,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-09 21:42:00,137,0.01000,128,0.8894,0.8389,production_candidate
25,85,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 18:09:00,122,0.00300,128,0.7967,0.7627,debug
26,95,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 10:21:00,224,0.00030,16,0.8767,0.8807,full_train
27,97,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,H100,2026-08-28 23:44:00,96,0.01000,32,0.8206,0.8271,augmentation
28,99,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-31 05:50:00,44,0.00010,128,0.8259,0.7769,full_train
29,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
30,104,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-17 12:27:00,198,0.00010,16,0.8879,0.8348,tuned
31,109,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-12 02:39:00,125,0.00030,128,0.7893,0.7389,debug
32,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
33,120,30,tabular_dropout_030,Никита Фролов,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,A100,2026-09-23 14:33:00,258,0.00300,16,0.8151,0.7922,production_candidate
34,127,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,completed,A100,2026-08-21 05:51:00,194,0.00030,128,0.8636,0.8130,augmentation
35,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
36,134,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-15 21:08:00,148,0.01000,32,0.8723,0.8665,tuned
37,136,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,A100,2026-08-31 04:10:00,178,0.01000,16,0.8106,0.7812,augmentation
38,137,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-01 10:27:00,78,0.00100,64,0.8903,0.8368,baseline
39,139,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-03 01:42:00,134,0.01000,16,0.7451,0.7006,debug
40,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
41,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
42,149,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-16 12:07:00,154,0.00100,128,0.8619,0.8500,tuned
43,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
44,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
45,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

In [83]:
query = '''
SELECT *
FROM run_overview
WHERE
    (
        status = 'completed'
        AND
        gpu = 'A100'
    )
    OR
    (
        status = 'completed'
        AND
        gpu = 'H100'
    )
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
3,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
4,17,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-04 08:35:00,59,0.01000,128,0.7296,0.7422,class_weight
5,25,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 11:00:00,198,0.00100,64,0.7210,0.6940,baseline
6,26,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 22:02:00,189,0.00010,32,0.8745,0.8376,augmentation
7,32,32,cv_baseline_032,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,H100,2026-09-07 09:47:00,127,0.00005,16,0.8400,0.8091,augmentation
8,33,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,A100,2026-09-14 10:14:00,60,0.00005,32,0.8462,0.8282,full_train
9,35,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 07:48:00,204,0.00100,32,0.8785,0.8335,production_candidate
10,38,38,tabular_baseline_038,Даниил Ли,Tabular,LightGBM,Gradient Boosting,Tabular,Credit Default,public,30000,completed,H100,2026-09-22 05:30:00,97,0.00005,16,0.8609,0.8400,fast_test
11,40,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 20:26:00,40,0.01000,128,0.8067,0.7747,augmentation
12,43,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-08-24 07:34:00,208,0.00010,64,0.8797,0.8213,class_weight
13,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate
14,47,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-02 16:34:00,10,0.00100,128,0.7452,0.7328,class_weight
15,49,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-04 03:34:00,72,0.00100,128,0.6711,0.6258,debug
16,50,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 07:04:00,50,0.00300,16,0.8237,0.7683,debug
17,52,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,A100,2026-08-30 03:36:00,257,0.00100,32,0.8795,0.8905,production_candidate
18,60,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-08-28 09:45:00,66,0.01000,16,0.8903,0.8975,production_candidate
19,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
20,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
21,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
22,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
23,78,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,H100,2026-09-15 15:20:00,231,0.00300,32,0.7480,0.7120,debug
24,80,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-09 21:42:00,137,0.01000,128,0.8894,0.8389,production_candidate
25,85,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 18:09:00,122,0.00300,128,0.7967,0.7627,debug
26,95,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 10:21:00,224,0.00030,16,0.8767,0.8807,full_train
27,97,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,H100,2026-08-28 23:44:00,96,0.01000,32,0.8206,0.8271,augmentation
28,99,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-31 05:50:00,44,0.00010,128,0.8259,0.7769,full_train
29,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
30,104,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-17 12:27:00,198,0.00010,16,0.8879,0.8348,tuned
31,109,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-12 02:39:00,125,0.00030,128,0.7893,0.7389,debug
32,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
33,120,30,tabular_dropout_030,Никита Фролов,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,A100,2026-09-23 14:33:00,258,0.00300,16,0.8151,0.7922,production_candidate
34,127,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,completed,A100,2026-08-21 05:51:00,194,0.00030,128,0.8636,0.8130,augmentation
35,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
36,134,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-15 21:08:00,148,0.01000,32,0.8723,0.8665,tuned
37,136,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,A100,2026-08-31 04:10:00,178,0.01000,16,0.8106,0.7812,augmentation
38,137,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-01 10:27:00,78,0.00100,64,0.8903,0.8368,baseline
39,139,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-03 01:42:00,134,0.01000,16,0.7451,0.7006,debug
40,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
41,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
42,149,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-16 12:07:00,154,0.00100,128,0.8619,0.8500,tuned
43,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
44,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
45,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

In [84]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    gpu IN ('A100', 'H100');
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
3,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
4,17,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-04 08:35:00,59,0.01000,128,0.7296,0.7422,class_weight
5,25,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 11:00:00,198,0.00100,64,0.7210,0.6940,baseline
6,26,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 22:02:00,189,0.00010,32,0.8745,0.8376,augmentation
7,32,32,cv_baseline_032,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,H100,2026-09-07 09:47:00,127,0.00005,16,0.8400,0.8091,augmentation
8,33,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,A100,2026-09-14 10:14:00,60,0.00005,32,0.8462,0.8282,full_train
9,35,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 07:48:00,204,0.00100,32,0.8785,0.8335,production_candidate
10,38,38,tabular_baseline_038,Даниил Ли,Tabular,LightGBM,Gradient Boosting,Tabular,Credit Default,public,30000,completed,H100,2026-09-22 05:30:00,97,0.00005,16,0.8609,0.8400,fast_test
11,40,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 20:26:00,40,0.01000,128,0.8067,0.7747,augmentation
12,43,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-08-24 07:34:00,208,0.00010,64,0.8797,0.8213,class_weight
13,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate
14,47,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-02 16:34:00,10,0.00100,128,0.7452,0.7328,class_weight
15,49,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-04 03:34:00,72,0.00100,128,0.6711,0.6258,debug
16,50,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 07:04:00,50,0.00300,16,0.8237,0.7683,debug
17,52,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,A100,2026-08-30 03:36:00,257,0.00100,32,0.8795,0.8905,production_candidate
18,60,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-08-28 09:45:00,66,0.01000,16,0.8903,0.8975,production_candidate
19,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
20,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
21,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
22,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
23,78,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,H100,2026-09-15 15:20:00,231,0.00300,32,0.7480,0.7120,debug
24,80,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-09 21:42:00,137,0.01000,128,0.8894,0.8389,production_candidate
25,85,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 18:09:00,122,0.00300,128,0.7967,0.7627,debug
26,95,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 10:21:00,224,0.00030,16,0.8767,0.8807,full_train
27,97,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,H100,2026-08-28 23:44:00,96,0.01000,32,0.8206,0.8271,augmentation
28,99,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-31 05:50:00,44,0.00010,128,0.8259,0.7769,full_train
29,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
30,104,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-17 12:27:00,198,0.00010,16,0.8879,0.8348,tuned
31,109,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-12 02:39:00,125,0.00030,128,0.7893,0.7389,debug
32,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
33,120,30,tabular_dropout_030,Никита Фролов,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,A100,2026-09-23 14:33:00,258,0.00300,16,0.8151,0.7922,production_candidate
34,127,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,completed,A100,2026-08-21 05:51:00,194,0.00030,128,0.8636,0.8130,augmentation
35,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
36,134,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-15 21:08:00,148,0.01000,32,0.8723,0.8665,tuned
37,136,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,A100,2026-08-31 04:10:00,178,0.01000,16,0.8106,0.7812,augmentation
38,137,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-01 10:27:00,78,0.00100,64,0.8903,0.8368,baseline
39,139,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-03 01:42:00,134,0.01000,16,0.7451,0.7006,debug
40,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
41,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
42,149,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-16 12:07:00,154,0.00100,128,0.8619,0.8500,tuned
43,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
44,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
45,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

### пара 2

##### задание 1

##### задание 2

##### задание 3

##### задание 4

##### задание 5

##### задание 6

##### задание 7

##### задание 8

# --

In [ ]:
connection.close()