# Иванов Матвей - подгруппа 1

### если читаете с телефона, откройте ПК версию
### извините за такой формат
хотел, чтобы таблицы выглядели нормально \
начала делать в ipynb из-за MarkDown и pandas, \
который позволяет красиво отоброжать таблицы, \
когда сделал, увидел, что в pdf это нормально не конвертируется \
и пришлось экспортировать в HTML, но с сохранением красоты и удобства, но в ПК версии \
если нужно, то переделаю в текстовый .sql

### подготовка

In [44]:
# подключили библиотеку
import sqlite3
import pandas as pd

In [45]:
def print_table(fetchall):
    for row in fetchall:
        print(row)

In [46]:
# настроили соединение и способ взаимодействия
connection = sqlite3.connect('ivanov_lab01.db')
cursor = connection.cursor()

In [47]:
# загрузили данные в нашу БД
cursor.executescript(open("ai_data_lab.sql").read())
connection.commit()

In [48]:
# проверили БД
query = '''
SELECT COUNT(*) AS rows_in_lab
FROM run_overview;
'''
pd.read_sql_query(query, connection)

   rows_in_lab
0          160

### пара 1

##### задание 1
Выведите первые 10 строк run_overview. Не перечисляйте столбцы вручную

In [49]:
query = '''
SELECT *
FROM run_overview
LIMIT 10;
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,1,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,RTX 4090,2026-08-31 15:51:00,38,0.00300,64,0.8618,0.8688,debug
1,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
2,3,3,tabular_class_weight_003,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Fraud Mini,internal,125000,completed,RTX 4090,2026-09-13 23:14:00,191,0.00010,128,0.8547,0.8013,full_train
3,4,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,T4,2026-09-04 08:19:00,127,0.00030,64,0.8055,0.8287,full_train
4,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
5,6,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,failed,T4,2026-09-04 21:23:00,17,0.00010,32,0.6171,NaN,production_candidate
6,7,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-28 09:10:00,195,0.00100,32,0.9198,0.8749,debug
7,8,8,cv_tuned_008,Дарья Новикова,CV,ResNet50,ResNet,CV,CIFAR-10,public,60000,completed,CPU,2026-09-01 11:02:00,165,0.00005,32,0.7537,0.7308,class_weight
8,9,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,CPU,2026-09-01 09:38:00,66,0.01000,32,0.8899,0.9042,fast_test
9,10,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-09-18 07:21:00,225,0.00010,64,0.5504,NaN,augmentation

##### задание 2
Выведите только run_id, model_name, dataset_name, task_type, status.

In [50]:
query = '''
SELECT run_id, model_name, dataset_name, task_type, status
FROM run_overview;
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

     run_id        model_name     dataset_name task_type     status
0         1        DistilBERT      RuSentiment       NLP  completed
1         2     ConvNeXt-Tiny     Cats vs Dogs        CV  completed
2         3      RandomForest       Fraud Mini   Tabular  completed
3         4       MobileNetV3     Cats vs Dogs        CV  completed
4         5          LightGBM   Customer Churn   Tabular  completed
..      ...               ...              ...       ...        ...
155     156      RandomForest   Customer Churn   Tabular     failed
156     157  DeBERTa-v3-small      RuSentiment       NLP    running
157     158          ResNet50     PlantVillage        CV  completed
158     159      RandomForest  Student Success   Tabular    running
159     160         BERT-base          AG News       NLP  completed

[160 rows x 5 columns]

##### задание 3
Получите уникальный список типов задач task_type.

In [51]:
query = '''
SELECT DISTINCT task_type
FROM run_overview;
'''
pd.read_sql_query(query, connection)

  task_type
0       NLP
1        CV
2   Tabular

##### задание 4
Получите уникальный список источников датасетов dataset_source.

In [52]:
query = '''
SELECT DISTINCT dataset_source
FROM run_overview;
'''
pd.read_sql_query(query, connection)

  dataset_source
0       internal
1         public

##### задание 5
Покажите только завершённые запуски (status = 'completed').

In [53]:
query = '''
SELECT *
FROM run_overview
WHERE status = 'completed';
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,1,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,RTX 4090,2026-08-31 15:51:00,38,0.00300,64,0.8618,0.8688,debug
1,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
2,3,3,tabular_class_weight_003,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Fraud Mini,internal,125000,completed,RTX 4090,2026-09-13 23:14:00,191,0.00010,128,0.8547,0.8013,full_train
3,4,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,T4,2026-09-04 08:19:00,127,0.00030,64,0.8055,0.8287,full_train
4,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,151,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,RTX 4090,2026-08-27 10:24:00,23,0.00005,16,0.9255,0.8660,full_train
103,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
104,154,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,T4,2026-09-14 19:46:00,268,0.00010,16,0.7997,0.7474,class_weight
105,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
106,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

##### задание 6
Найдите запуски с f1_score не ниже 0.85.

In [54]:
query = '''
SELECT *
FROM run_overview
WHERE f1_score >= 0.85;
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,1,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,RTX 4090,2026-08-31 15:51:00,38,0.00300,64,0.8618,0.8688,debug
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,7,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-28 09:10:00,195,0.00100,32,0.9198,0.8749,debug
3,9,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,CPU,2026-09-01 09:38:00,66,0.01000,32,0.8899,0.9042,fast_test
4,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
5,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
6,14,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,L40S,2026-09-17 17:04:00,233,0.00010,16,0.8477,0.8500,debug
7,16,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,T4,2026-08-30 09:12:00,184,0.00100,64,0.9850,0.9800,full_train
8,18,18,cv_new_features_018,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,RTX 4090,2026-08-24 14:27:00,69,0.01000,64,0.8670,0.8915,tuned
9,20,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,CPU,2026-09-28 09:32:00,241,0.01000,64,0.9340,0.8968,production_candidate
10,22,22,nlp_class_weight_022,Иван Ким,NLP,DeBERTa-v3-small,DeBERTa,NLP,RuSentiment,internal,31000,completed,T4,2026-09-18 18:51:00,130,0.00010,16,0.9291,0.9301,tuned
11,24,24,tabular_tuned_024,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Student Success,internal,18000,completed,L40S,2026-08-29 16:19:00,264,0.00030,128,0.8810,0.8698,baseline
12,27,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,RTX 4090,2026-08-29 15:47:00,135,0.00300,32,0.9226,0.8859,production_candidate
13,28,28,cv_lr_sweep_028,Алексей Пак,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,T4,2026-09-09 07:55:00,276,0.00030,64,0.9403,0.9514,full_train
14,39,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,T4,2026-09-23 17:21:00,149,0.01000,32,0.8938,0.9127,fast_test
15,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate
16,51,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,completed,T4,2026-09-04 16:37:00,228,0.00030,64,0.9587,0.9498,class_weight
17,52,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,A100,2026-08-30 03:36:00,257,0.00100,32,0.8795,0.8905,production_candidate
18,57,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,CPU,2026-08-23 05:08:00,9,0.00010,128,0.8668,0.8610,production_candidate
19,58,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,RTX 4090,2026-09-18 11:48:00,73,0.00300,64,0.9412,0.9510,tuned
20,59,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,T4,2026-09-19 16:06:00,199,0.00010,32,0.9850,0.9695,fast_test
21,60,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-08-28 09:45:00,66,0.01000,16,0.8903,0.8975,production_candidate
22,61,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-29 18:01:00,174,0.00010,16,0.9750,0.9697,class_weight
23,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
24,66,21,tabular_tuned_021,Даниил Ли,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,T4,2026-09-16 10:11:00,249,0.00100,64,0.9254,0.9113,production_candidate
25,70,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,L40S,2026-09-21 17:48:00,127,0.00100,16,0.9452,0.8863,class_weight
26,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
27,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
28,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
29,79,34,nlp_sanity_check_034,Максим Чернов,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,L40S,2026-09-03 08:28:00,112,0.00030,16,0.9388,0.8891,augmentation
30,84,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,L40S,2026-09-20 21:58:00,234,0.01000,64,0.8972,0.9012,baseline
31,93,3,tabular_class_weight_003,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Fraud Mini,internal,125000,completed,T4,2026-09-10 20:48:00,213,0.00100,16,0.9024,0.8694,full_train
32,95,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 10:21:00,224,0.00030,16,0.8767,0.8807,full_train
33,96,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,completed,T4,2026-09-07 14:48:00,119,0.01000,128,0.8801,0.8857,baseline
34,100,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,completed,L40S,2026-09-17 18:05:00,38,0.00300,32,0.8901,0.8604,baseline
35,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
36,105,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,L40S,2026-08-27 21:43:00,180,0.00030,64,0.9503,0.9256,augmentation
37,114,24,tabular_tuned_024,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Student Success,internal,18000,completed,T4,2026-08-27 10:11:00,167,0.00005,16,0.9290,0.8854,debug
38,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
39,126,36,tabular_sanity_check_036,Мария Орлова,Tabular,LogisticRegression,Linear,Tabular,Fraud Mini,internal,125000,completed,T4,2026-09-25 02:51:00,162,0.00100,128,0.9637,0.9614,debug
40,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
41,131,41,tabular_lr_sweep_041,Полина Кравцова,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,RTX 4090,2026-09-14 04:34:00,189,0.00300,64,0.8516,0.8672,full_train
42,134,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-15 21:08:00,148,0.01000,32,0.8723,0.8665,tuned
43,142,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-29 02:37:00,271,0.00010,32,0.9415,0.8897,debug
44,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
45,146,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,completed,L40S,2026-08-28 22:11:00,238,0.00010,16,0.9590,0.9475,debug
46,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
47,149,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-16 12:07:00,154,0.00100,128,0.8619,0.8500,tuned
48,151,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,RTX 4090,2026-08-27 10:24:00,23,0.00005,16,0.9255,0.8660,full_train
49,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
50,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
51,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

##### задание 7
Найдите запуски, выполненные на A100 или H100. Используйте IN.

In [55]:
query = '''
SELECT *
FROM run_overview
WHERE gpu IN ('A100', 'H100');
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,10,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-09-18 07:21:00,225,0.00010,64,0.5504,NaN,augmentation
3,11,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-08-28 01:44:00,199,0.00005,64,NaN,NaN,baseline
4,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,156,21,tabular_tuned_021,Даниил Ли,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,failed,A100,2026-09-14 13:14:00,234,0.00010,128,NaN,NaN,tuned
66,157,22,nlp_class_weight_022,Иван Ким,NLP,DeBERTa-v3-small,DeBERTa,NLP,RuSentiment,internal,31000,running,A100,2026-09-18 12:31:00,133,0.00030,64,NaN,NaN,production_candidate
67,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
68,159,24,tabular_tuned_024,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Student Success,internal,18000,running,A100,2026-08-27 12:57:00,248,0.00100,32,NaN,NaN,baseline
69,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

##### задание 8
Покажите 5 лучших завершённых запусков по f1_score.

In [56]:
query = '''
SELECT *
FROM run_overview
WHERE status = 'completed'
ORDER BY f1_score DESC
LIMIT 5;
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,16,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,T4,2026-08-30 09:12:00,184,0.0010,64,0.9850,0.9800,full_train
1,61,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-29 18:01:00,174,0.0001,16,0.9750,0.9697,class_weight
2,59,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,T4,2026-09-19 16:06:00,199,0.0001,32,0.9850,0.9695,fast_test
3,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.0001,32,0.9721,0.9654,production_candidate
4,126,36,tabular_sanity_check_036,Мария Орлова,Tabular,LogisticRegression,Linear,Tabular,Fraud Mini,internal,125000,completed,T4,2026-09-25 02:51:00,162,0.0010,128,0.9637,0.9614,debug

##### задание 9
Выведите model_name, accuracy и новый столбец accuracy_percent = accuracy * 100

In [57]:
query = '''
SELECT model_name, accuracy, accuracy * 100 AS accuracy_percent
FROM run_overview;
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

           model_name  accuracy  accuracy_percent
0          DistilBERT    0.8618             86.18
1       ConvNeXt-Tiny    0.7634             76.34
2        RandomForest    0.8547             85.47
3         MobileNetV3    0.8055             80.55
4            LightGBM    0.9473             94.73
..                ...       ...               ...
155      RandomForest       NaN               NaN
156  DeBERTa-v3-small       NaN               NaN
157          ResNet50    0.9058             90.58
158      RandomForest       NaN               NaN
159         BERT-base    0.9721             97.21

[160 rows x 3 columns]

##### задание 10
Найдите завершённые запуски на A100 или H100 с accuracy >= 0.90. Сначала должны идти лучшие значения accuracy.

In [58]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    gpu IN ('A100', 'H100')
    AND
    accuracy >= 0.90
ORDER BY accuracy DESC;
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate
1,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
2,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
3,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
4,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
5,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
6,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
7,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
8,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
9,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
10,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
11,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
12,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
13,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate

### Expert Track 1

##### EXPERT A
Проверьте утверждение: «Если используют H100 то результат всегда высокий». Найдите завершённые эксперименты на H100-запуски где f1_score < 0.75. Если строки есть — сформулируйте, подтверждается ли утверждение или опровергается.

утверждение опровергается, так как есть завершённые запуски на H100 с f1_score < 0.75, значит GPU H100 не гарантирует высокий результат

In [59]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    gpu = 'H100'
    AND
    f1_score < 0.75
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,78,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,H100,2026-09-15 15:20:00,231,0.0030,32,0.7480,0.7120,debug
1,109,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-12 02:39:00,125,0.0003,128,0.7893,0.7389,debug

##### EXPERT B
задание: Найдите ошибку в логике запроса ниже. Руководитель считает, что он возвращает только завершённые запуски на A100 и H100. Проверьте это и исправьте. \
SELECT * \
FROM run_overview \
WHERE status = 'completed' \
  AND gpu = 'A100' \
   OR gpu = 'H100';

при таком запросе у нас либо завершённое на A100, либо на H100 (без упоминания завершённости)

In [60]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    gpu = 'A100'
    OR
    gpu = 'H100'

'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,10,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-09-18 07:21:00,225,0.00010,64,0.5504,NaN,augmentation
3,11,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-08-28 01:44:00,199,0.00005,64,NaN,NaN,baseline
4,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
5,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
6,17,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-04 08:35:00,59,0.01000,128,0.7296,0.7422,class_weight
7,23,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,cancelled,H100,2026-09-06 06:09:00,108,0.00300,64,NaN,NaN,augmentation
8,25,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 11:00:00,198,0.00100,64,0.7210,0.6940,baseline
9,26,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 22:02:00,189,0.00010,32,0.8745,0.8376,augmentation
10,32,32,cv_baseline_032,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,H100,2026-09-07 09:47:00,127,0.00005,16,0.8400,0.8091,augmentation
11,33,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,A100,2026-09-14 10:14:00,60,0.00005,32,0.8462,0.8282,full_train
12,34,34,nlp_sanity_check_034,Максим Чернов,NLP,BERT-base,BERT,NLP,AG News,public,120000,failed,H100,2026-09-03 13:27:00,187,0.00030,16,NaN,NaN,production_candidate
13,35,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 07:48:00,204,0.00100,32,0.8785,0.8335,production_candidate
14,38,38,tabular_baseline_038,Даниил Ли,Tabular,LightGBM,Gradient Boosting,Tabular,Credit Default,public,30000,completed,H100,2026-09-22 05:30:00,97,0.00005,16,0.8609,0.8400,fast_test
15,40,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 20:26:00,40,0.01000,128,0.8067,0.7747,augmentation
16,43,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-08-24 07:34:00,208,0.00010,64,0.8797,0.8213,class_weight
17,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate
18,47,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-02 16:34:00,10,0.00100,128,0.7452,0.7328,class_weight
19,49,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-04 03:34:00,72,0.00100,128,0.6711,0.6258,debug
20,50,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 07:04:00,50,0.00300,16,0.8237,0.7683,debug
21,52,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,A100,2026-08-30 03:36:00,257,0.00100,32,0.8795,0.8905,production_candidate
22,60,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-08-28 09:45:00,66,0.01000,16,0.8903,0.8975,production_candidate
23,64,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,failed,H100,2026-09-14 05:17:00,94,0.00030,32,NaN,NaN,production_candidate
24,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
25,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
26,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
27,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
28,78,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,H100,2026-09-15 15:20:00,231,0.00300,32,0.7480,0.7120,debug
29,80,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-09 21:42:00,137,0.01000,128,0.8894,0.8389,production_candidate
30,85,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 18:09:00,122,0.00300,128,0.7967,0.7627,debug
31,95,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 10:21:00,224,0.00030,16,0.8767,0.8807,full_train
32,97,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,H100,2026-08-28 23:44:00,96,0.01000,32,0.8206,0.8271,augmentation
33,99,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-31 05:50:00,44,0.00010,128,0.8259,0.7769,full_train
34,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
35,104,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-17 12:27:00,198,0.00010,16,0.8879,0.8348,tuned
36,109,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-12 02:39:00,125,0.00030,128,0.7893,0.7389,debug
37,115,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,cancelled,H100,2026-09-25 06:37:00,88,0.00100,64,NaN,NaN,tuned
38,117,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,running,H100,2026-08-30 03:22:00,77,0.00010,128,0.6632,NaN,production_candidate
39,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
40,120,30,tabular_dropout_030,Никита Фролов,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,A100,2026-09-23 14:33:00,258,0.00300,16,0.8151,0.7922,production_candidate
41,124,34,nlp_sanity_check_034,Максим Чернов,NLP,BERT-base,BERT,NLP,AG News,public,120000,failed,H100,2026-09-06 01:27:00,151,0.00100,16,NaN,NaN,full_train
42,127,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,completed,A100,2026-08-21 05:51:00,194,0.00030,128,0.8636,0.8130,augmentation
43,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
44,133,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,failed,H100,2026-08-25 06:58:00,9,0.00005,64,0.6604,NaN,debug
45,134,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-15 21:08:00,148,0.01000,32,0.8723,0.8665,tuned
46,136,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,A100,2026-08-31 04:10:00,178,0.01000,16,0.8106,0.7812,augmentation
47,137,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-01 10:27:00,78,0.00100,64,0.8903,0.8368,baseline
48,139,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-03 01:42:00,134,0.01000,16,0.7451,0.7006,debug
49,143,8,cv_tuned_008,Дарья Новикова,CV,ResNet50,ResNet,CV,CIFAR-10,public,60000,failed,H100,2026-08-29 13:20:00,73,0.00030,16,0.6308,NaN,tuned
50,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
51,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
52,149,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-16 12:07:00,154,0.00100,128,0.8619,0.8500,tuned
53,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
54,155,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-09-24 09:37:00,28,0.00010,64,NaN,NaN,debug
55,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
56,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

In [61]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    gpu IN ('A100', 'H100');
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
3,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
4,17,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-04 08:35:00,59,0.01000,128,0.7296,0.7422,class_weight
5,25,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 11:00:00,198,0.00100,64,0.7210,0.6940,baseline
6,26,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 22:02:00,189,0.00010,32,0.8745,0.8376,augmentation
7,32,32,cv_baseline_032,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,H100,2026-09-07 09:47:00,127,0.00005,16,0.8400,0.8091,augmentation
8,33,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,A100,2026-09-14 10:14:00,60,0.00005,32,0.8462,0.8282,full_train
9,35,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 07:48:00,204,0.00100,32,0.8785,0.8335,production_candidate
10,38,38,tabular_baseline_038,Даниил Ли,Tabular,LightGBM,Gradient Boosting,Tabular,Credit Default,public,30000,completed,H100,2026-09-22 05:30:00,97,0.00005,16,0.8609,0.8400,fast_test
11,40,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 20:26:00,40,0.01000,128,0.8067,0.7747,augmentation
12,43,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-08-24 07:34:00,208,0.00010,64,0.8797,0.8213,class_weight
13,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate
14,47,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-02 16:34:00,10,0.00100,128,0.7452,0.7328,class_weight
15,49,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-04 03:34:00,72,0.00100,128,0.6711,0.6258,debug
16,50,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 07:04:00,50,0.00300,16,0.8237,0.7683,debug
17,52,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,A100,2026-08-30 03:36:00,257,0.00100,32,0.8795,0.8905,production_candidate
18,60,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-08-28 09:45:00,66,0.01000,16,0.8903,0.8975,production_candidate
19,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
20,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
21,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
22,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
23,78,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,H100,2026-09-15 15:20:00,231,0.00300,32,0.7480,0.7120,debug
24,80,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-09 21:42:00,137,0.01000,128,0.8894,0.8389,production_candidate
25,85,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 18:09:00,122,0.00300,128,0.7967,0.7627,debug
26,95,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 10:21:00,224,0.00030,16,0.8767,0.8807,full_train
27,97,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,H100,2026-08-28 23:44:00,96,0.01000,32,0.8206,0.8271,augmentation
28,99,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-31 05:50:00,44,0.00010,128,0.8259,0.7769,full_train
29,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
30,104,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-17 12:27:00,198,0.00010,16,0.8879,0.8348,tuned
31,109,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-12 02:39:00,125,0.00030,128,0.7893,0.7389,debug
32,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
33,120,30,tabular_dropout_030,Никита Фролов,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,A100,2026-09-23 14:33:00,258,0.00300,16,0.8151,0.7922,production_candidate
34,127,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,completed,A100,2026-08-21 05:51:00,194,0.00030,128,0.8636,0.8130,augmentation
35,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
36,134,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-15 21:08:00,148,0.01000,32,0.8723,0.8665,tuned
37,136,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,A100,2026-08-31 04:10:00,178,0.01000,16,0.8106,0.7812,augmentation
38,137,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-01 10:27:00,78,0.00100,64,0.8903,0.8368,baseline
39,139,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-03 01:42:00,134,0.01000,16,0.7451,0.7006,debug
40,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
41,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
42,149,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-16 12:07:00,154,0.00100,128,0.8619,0.8500,tuned
43,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
44,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
45,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

##### EXPERT C
Если SQL для вас давно знаком: решите Expert B минимум двумя способами и объясните, какой вариант легче читать и поддерживать.

третий вариант проще в чтении и поддержке, потому что написан более лаконичнее и используется лишь одна логическая операция, в остальных вариантах с 3-4 операциями легко запустаться

In [62]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    (
        gpu = 'A100'
        OR
        gpu = 'H100'
    )
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
3,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
4,17,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-04 08:35:00,59,0.01000,128,0.7296,0.7422,class_weight
5,25,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 11:00:00,198,0.00100,64,0.7210,0.6940,baseline
6,26,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 22:02:00,189,0.00010,32,0.8745,0.8376,augmentation
7,32,32,cv_baseline_032,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,H100,2026-09-07 09:47:00,127,0.00005,16,0.8400,0.8091,augmentation
8,33,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,A100,2026-09-14 10:14:00,60,0.00005,32,0.8462,0.8282,full_train
9,35,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 07:48:00,204,0.00100,32,0.8785,0.8335,production_candidate
10,38,38,tabular_baseline_038,Даниил Ли,Tabular,LightGBM,Gradient Boosting,Tabular,Credit Default,public,30000,completed,H100,2026-09-22 05:30:00,97,0.00005,16,0.8609,0.8400,fast_test
11,40,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 20:26:00,40,0.01000,128,0.8067,0.7747,augmentation
12,43,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-08-24 07:34:00,208,0.00010,64,0.8797,0.8213,class_weight
13,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate
14,47,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-02 16:34:00,10,0.00100,128,0.7452,0.7328,class_weight
15,49,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-04 03:34:00,72,0.00100,128,0.6711,0.6258,debug
16,50,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 07:04:00,50,0.00300,16,0.8237,0.7683,debug
17,52,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,A100,2026-08-30 03:36:00,257,0.00100,32,0.8795,0.8905,production_candidate
18,60,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-08-28 09:45:00,66,0.01000,16,0.8903,0.8975,production_candidate
19,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
20,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
21,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
22,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
23,78,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,H100,2026-09-15 15:20:00,231,0.00300,32,0.7480,0.7120,debug
24,80,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-09 21:42:00,137,0.01000,128,0.8894,0.8389,production_candidate
25,85,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 18:09:00,122,0.00300,128,0.7967,0.7627,debug
26,95,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 10:21:00,224,0.00030,16,0.8767,0.8807,full_train
27,97,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,H100,2026-08-28 23:44:00,96,0.01000,32,0.8206,0.8271,augmentation
28,99,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-31 05:50:00,44,0.00010,128,0.8259,0.7769,full_train
29,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
30,104,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-17 12:27:00,198,0.00010,16,0.8879,0.8348,tuned
31,109,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-12 02:39:00,125,0.00030,128,0.7893,0.7389,debug
32,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
33,120,30,tabular_dropout_030,Никита Фролов,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,A100,2026-09-23 14:33:00,258,0.00300,16,0.8151,0.7922,production_candidate
34,127,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,completed,A100,2026-08-21 05:51:00,194,0.00030,128,0.8636,0.8130,augmentation
35,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
36,134,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-15 21:08:00,148,0.01000,32,0.8723,0.8665,tuned
37,136,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,A100,2026-08-31 04:10:00,178,0.01000,16,0.8106,0.7812,augmentation
38,137,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-01 10:27:00,78,0.00100,64,0.8903,0.8368,baseline
39,139,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-03 01:42:00,134,0.01000,16,0.7451,0.7006,debug
40,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
41,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
42,149,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-16 12:07:00,154,0.00100,128,0.8619,0.8500,tuned
43,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
44,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
45,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

In [63]:
query = '''
SELECT *
FROM run_overview
WHERE
    (
        status = 'completed'
        AND
        gpu = 'A100'
    )
    OR
    (
        status = 'completed'
        AND
        gpu = 'H100'
    )
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
3,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
4,17,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-04 08:35:00,59,0.01000,128,0.7296,0.7422,class_weight
5,25,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 11:00:00,198,0.00100,64,0.7210,0.6940,baseline
6,26,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 22:02:00,189,0.00010,32,0.8745,0.8376,augmentation
7,32,32,cv_baseline_032,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,H100,2026-09-07 09:47:00,127,0.00005,16,0.8400,0.8091,augmentation
8,33,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,A100,2026-09-14 10:14:00,60,0.00005,32,0.8462,0.8282,full_train
9,35,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 07:48:00,204,0.00100,32,0.8785,0.8335,production_candidate
10,38,38,tabular_baseline_038,Даниил Ли,Tabular,LightGBM,Gradient Boosting,Tabular,Credit Default,public,30000,completed,H100,2026-09-22 05:30:00,97,0.00005,16,0.8609,0.8400,fast_test
11,40,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 20:26:00,40,0.01000,128,0.8067,0.7747,augmentation
12,43,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-08-24 07:34:00,208,0.00010,64,0.8797,0.8213,class_weight
13,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate
14,47,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-02 16:34:00,10,0.00100,128,0.7452,0.7328,class_weight
15,49,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-04 03:34:00,72,0.00100,128,0.6711,0.6258,debug
16,50,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 07:04:00,50,0.00300,16,0.8237,0.7683,debug
17,52,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,A100,2026-08-30 03:36:00,257,0.00100,32,0.8795,0.8905,production_candidate
18,60,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-08-28 09:45:00,66,0.01000,16,0.8903,0.8975,production_candidate
19,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
20,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
21,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
22,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
23,78,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,H100,2026-09-15 15:20:00,231,0.00300,32,0.7480,0.7120,debug
24,80,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-09 21:42:00,137,0.01000,128,0.8894,0.8389,production_candidate
25,85,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 18:09:00,122,0.00300,128,0.7967,0.7627,debug
26,95,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 10:21:00,224,0.00030,16,0.8767,0.8807,full_train
27,97,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,H100,2026-08-28 23:44:00,96,0.01000,32,0.8206,0.8271,augmentation
28,99,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-31 05:50:00,44,0.00010,128,0.8259,0.7769,full_train
29,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
30,104,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-17 12:27:00,198,0.00010,16,0.8879,0.8348,tuned
31,109,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-12 02:39:00,125,0.00030,128,0.7893,0.7389,debug
32,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
33,120,30,tabular_dropout_030,Никита Фролов,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,A100,2026-09-23 14:33:00,258,0.00300,16,0.8151,0.7922,production_candidate
34,127,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,completed,A100,2026-08-21 05:51:00,194,0.00030,128,0.8636,0.8130,augmentation
35,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
36,134,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-15 21:08:00,148,0.01000,32,0.8723,0.8665,tuned
37,136,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,A100,2026-08-31 04:10:00,178,0.01000,16,0.8106,0.7812,augmentation
38,137,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-01 10:27:00,78,0.00100,64,0.8903,0.8368,baseline
39,139,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-03 01:42:00,134,0.01000,16,0.7451,0.7006,debug
40,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
41,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
42,149,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-16 12:07:00,154,0.00100,128,0.8619,0.8500,tuned
43,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
44,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
45,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

In [64]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    gpu IN ('A100', 'H100');
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,2,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-01 10:05:00,183,0.00030,32,0.7634,0.7586,fast_test
1,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
2,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
3,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
4,17,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-04 08:35:00,59,0.01000,128,0.7296,0.7422,class_weight
5,25,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 11:00:00,198,0.00100,64,0.7210,0.6940,baseline
6,26,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 22:02:00,189,0.00010,32,0.8745,0.8376,augmentation
7,32,32,cv_baseline_032,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,H100,2026-09-07 09:47:00,127,0.00005,16,0.8400,0.8091,augmentation
8,33,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,A100,2026-09-14 10:14:00,60,0.00005,32,0.8462,0.8282,full_train
9,35,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 07:48:00,204,0.00100,32,0.8785,0.8335,production_candidate
10,38,38,tabular_baseline_038,Даниил Ли,Tabular,LightGBM,Gradient Boosting,Tabular,Credit Default,public,30000,completed,H100,2026-09-22 05:30:00,97,0.00005,16,0.8609,0.8400,fast_test
11,40,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 20:26:00,40,0.01000,128,0.8067,0.7747,augmentation
12,43,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-08-24 07:34:00,208,0.00010,64,0.8797,0.8213,class_weight
13,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate
14,47,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-02 16:34:00,10,0.00100,128,0.7452,0.7328,class_weight
15,49,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-04 03:34:00,72,0.00100,128,0.6711,0.6258,debug
16,50,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 07:04:00,50,0.00300,16,0.8237,0.7683,debug
17,52,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,A100,2026-08-30 03:36:00,257,0.00100,32,0.8795,0.8905,production_candidate
18,60,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-08-28 09:45:00,66,0.01000,16,0.8903,0.8975,production_candidate
19,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
20,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
21,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
22,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
23,78,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,H100,2026-09-15 15:20:00,231,0.00300,32,0.7480,0.7120,debug
24,80,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-09 21:42:00,137,0.01000,128,0.8894,0.8389,production_candidate
25,85,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 18:09:00,122,0.00300,128,0.7967,0.7627,debug
26,95,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 10:21:00,224,0.00030,16,0.8767,0.8807,full_train
27,97,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,H100,2026-08-28 23:44:00,96,0.01000,32,0.8206,0.8271,augmentation
28,99,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-31 05:50:00,44,0.00010,128,0.8259,0.7769,full_train
29,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
30,104,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-17 12:27:00,198,0.00010,16,0.8879,0.8348,tuned
31,109,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-12 02:39:00,125,0.00030,128,0.7893,0.7389,debug
32,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
33,120,30,tabular_dropout_030,Никита Фролов,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,A100,2026-09-23 14:33:00,258,0.00300,16,0.8151,0.7922,production_candidate
34,127,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,completed,A100,2026-08-21 05:51:00,194,0.00030,128,0.8636,0.8130,augmentation
35,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
36,134,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-15 21:08:00,148,0.01000,32,0.8723,0.8665,tuned
37,136,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,A100,2026-08-31 04:10:00,178,0.01000,16,0.8106,0.7812,augmentation
38,137,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-01 10:27:00,78,0.00100,64,0.8903,0.8368,baseline
39,139,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-03 01:42:00,134,0.01000,16,0.7451,0.7006,debug
40,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
41,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
42,149,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-16 12:07:00,154,0.00100,128,0.8619,0.8500,tuned
43,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate
44,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
45,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

### пара 2

##### задание 1
Покажите все запуски, которые НЕ имеют статуса completed. Используйте NOT или <>.

In [65]:
query = '''
SELECT *
FROM run_overview
WHERE
    NOT status = 'completed';
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,6,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,failed,T4,2026-09-04 21:23:00,17,0.00010,32,0.6171,NaN,production_candidate
1,10,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-09-18 07:21:00,225,0.00010,64,0.5504,NaN,augmentation
2,11,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-08-28 01:44:00,199,0.00005,64,NaN,NaN,baseline
3,19,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,cancelled,L40S,2026-09-11 21:23:00,247,0.00100,128,NaN,NaN,production_candidate
4,23,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,cancelled,H100,2026-09-06 06:09:00,108,0.00300,64,NaN,NaN,augmentation
5,29,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,cancelled,RTX 4090,2026-09-17 10:32:00,60,0.00100,128,0.6162,NaN,augmentation
6,31,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,failed,CPU,2026-09-24 19:57:00,207,0.00010,32,NaN,NaN,production_candidate
7,34,34,nlp_sanity_check_034,Максим Чернов,NLP,BERT-base,BERT,NLP,AG News,public,120000,failed,H100,2026-09-03 13:27:00,187,0.00030,16,NaN,NaN,production_candidate
8,36,36,tabular_sanity_check_036,Мария Орлова,Tabular,LogisticRegression,Linear,Tabular,Fraud Mini,internal,125000,failed,A100,2026-09-24 09:17:00,77,0.01000,16,NaN,NaN,class_weight
9,37,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,cancelled,A100,2026-08-22 23:02:00,101,0.00030,16,NaN,0.6992,full_train
10,42,42,tabular_sanity_check_042,Мария Орлова,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,failed,T4,2026-09-15 03:32:00,226,0.00005,32,0.5982,0.6939,class_weight
11,53,8,cv_tuned_008,Дарья Новикова,CV,ResNet50,ResNet,CV,CIFAR-10,public,60000,running,L40S,2026-08-30 11:57:00,187,0.00300,32,NaN,NaN,debug
12,54,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,failed,CPU,2026-08-29 17:22:00,143,0.00010,128,NaN,NaN,tuned
13,56,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,cancelled,CPU,2026-08-27 08:58:00,185,0.01000,16,0.6650,NaN,tuned
14,62,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,running,CPU,2026-09-05 14:23:00,127,0.01000,16,NaN,NaN,class_weight
15,64,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,failed,H100,2026-09-14 05:17:00,94,0.00030,32,NaN,NaN,production_candidate
16,67,22,nlp_class_weight_022,Иван Ким,NLP,DeBERTa-v3-small,DeBERTa,NLP,RuSentiment,internal,31000,running,L40S,2026-09-20 19:36:00,133,0.00100,32,NaN,NaN,fast_test
17,73,28,cv_lr_sweep_028,Алексей Пак,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,failed,A100,2026-09-11 08:11:00,92,0.00300,16,NaN,NaN,production_candidate
18,74,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,failed,A100,2026-09-18 11:17:00,200,0.00300,16,NaN,NaN,augmentation
19,86,41,tabular_lr_sweep_041,Полина Кравцова,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,running,CPU,2026-09-13 04:34:00,77,0.00030,16,NaN,0.6530,baseline
20,88,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,cancelled,L40S,2026-08-23 20:56:00,252,0.00005,16,NaN,NaN,production_candidate
21,90,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,cancelled,A100,2026-09-18 10:12:00,166,0.00030,16,NaN,NaN,production_candidate
22,91,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,failed,T4,2026-08-29 21:26:00,64,0.00300,128,0.6610,NaN,debug
23,92,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,running,T4,2026-09-03 18:07:00,14,0.00030,32,0.7359,NaN,full_train
24,94,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,cancelled,CPU,2026-09-04 04:37:00,174,0.00005,64,NaN,NaN,baseline
25,101,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,cancelled,L40S,2026-08-27 10:23:00,118,0.00005,32,NaN,NaN,production_candidate
26,103,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,running,A100,2026-09-19 13:27:00,174,0.00100,64,NaN,NaN,augmentation
27,107,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,running,RTX 4090,2026-09-05 09:59:00,246,0.00100,128,NaN,0.5307,baseline
28,108,18,cv_new_features_018,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,running,T4,2026-08-25 09:53:00,256,0.00300,64,0.7032,0.7765,production_candidate
29,110,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,failed,RTX 4090,2026-09-25 19:44:00,200,0.00010,128,NaN,NaN,class_weight
30,112,22,nlp_class_weight_022,Иван Ким,NLP,DeBERTa-v3-small,DeBERTa,NLP,RuSentiment,internal,31000,running,L40S,2026-09-20 15:51:00,194,0.01000,128,NaN,NaN,production_candidate
31,113,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,cancelled,T4,2026-09-08 06:43:00,134,0.01000,128,NaN,NaN,class_weight
32,115,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,cancelled,H100,2026-09-25 06:37:00,88,0.00100,64,NaN,NaN,tuned
33,116,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,cancelled,A100,2026-09-20 11:47:00,181,0.00100,16,NaN,NaN,debug
34,117,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,running,H100,2026-08-30 03:22:00,77,0.00010,128,0.6632,NaN,production_candidate
35,118,28,cv_lr_sweep_028,Алексей Пак,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,running,RTX 4090,2026-09-10 09:44:00,63,0.00300,32,0.8057,0.7689,fast_test
36,121,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,failed,T4,2026-09-26 20:42:00,175,0.00030,128,NaN,NaN,full_train
37,124,34,nlp_sanity_check_034,Максим Чернов,NLP,BERT-base,BERT,NLP,AG News,public,120000,failed,H100,2026-09-06 01:27:00,151,0.00100,16,NaN,NaN,full_train
38,125,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,cancelled,L40S,2026-09-10 16:49:00,28,0.00300,128,NaN,NaN,production_candidate
39,130,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,cancelled,A100,2026-09-02 11:11:00,71,0.00100,32,NaN,0.7857,class_weight
40,132,42,tabular_sanity_check_042,Мария Орлова,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,running,A100,2026-09-13 13:13:00,243,0.00010,64,NaN,NaN,fast_test
41,133,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,failed,H100,2026-08-25 06:58:00,9,0.00005,64,0.6604,NaN,debug
42,135,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,running,RTX 4090,2026-09-17 09:17:00,31,0.00005,64,NaN,NaN,tuned
43,138,3,tabular_class_weight_003,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Fraud Mini,internal,125000,failed,L40S,2026-09-14 01:20:00,214,0.00300,32,NaN,NaN,tuned
44,140,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,failed,A100,2026-08-31 22:56:00,50,0.00005,32,NaN,NaN,baseline
45,143,8,cv_tuned_008,Дарья Новикова,CV,ResNet50,ResNet,CV,CIFAR-10,public,60000,failed,H100,2026-08-29 13:20:00,73,0.00030,16,0.6308,NaN,tuned
46,145,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,failed,L40S,2026-09-19 15:42:00,53,0.00300,32,NaN,0.6021,full_train
47,148,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,running,T4,2026-09-18 00:24:00,244,0.01000,64,0.8191,NaN,full_train
48,153,18,cv_new_features_018,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,failed,RTX 4090,2026-08-23 10:24:00,51,0.00010,16,NaN,NaN,augmentation
49,155,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-09-24 09:37:00,28,0.00010,64,NaN,NaN,debug
50,156,21,tabular_tuned_021,Даниил Ли,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,failed,A100,2026-09-14 13:14:00,234,0.00010,128,NaN,NaN,tuned
51,157,22,nlp_class_weight_022,Иван Ким,NLP,DeBERTa-v3-small,DeBERTa,NLP,RuSentiment,internal,31000,running,A100,2026-09-18 12:31:00,133,0.00030,64,NaN,NaN,production_candidate
52,159,24,tabular_tuned_024,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Student Success,internal,18000,running,A100,2026-08-27 12:57:00,248,0.00100,32,NaN,NaN,baseline

##### задание 2
Покажите запуски, выполненные не на A100 и не на H100. Используйте NOT IN.

In [66]:
query = '''
SELECT *
FROM run_overview
WHERE
    gpu NOT IN ('A100', 'H100');
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,1,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,RTX 4090,2026-08-31 15:51:00,38,0.00300,64,0.8618,0.8688,debug
1,3,3,tabular_class_weight_003,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Fraud Mini,internal,125000,completed,RTX 4090,2026-09-13 23:14:00,191,0.00010,128,0.8547,0.8013,full_train
2,4,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,T4,2026-09-04 08:19:00,127,0.00030,64,0.8055,0.8287,full_train
3,6,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,failed,T4,2026-09-04 21:23:00,17,0.00010,32,0.6171,NaN,production_candidate
4,7,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-28 09:10:00,195,0.00100,32,0.9198,0.8749,debug
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,148,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,running,T4,2026-09-18 00:24:00,244,0.01000,64,0.8191,NaN,full_train
86,150,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,RTX 4090,2026-08-28 15:05:00,106,0.00010,128,0.8319,0.8462,tuned
87,151,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,RTX 4090,2026-08-27 10:24:00,23,0.00005,16,0.9255,0.8660,full_train
88,153,18,cv_new_features_018,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,failed,RTX 4090,2026-08-23 10:24:00,51,0.00010,16,NaN,NaN,augmentation
89,154,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,T4,2026-09-14 19:46:00,268,0.00010,16,0.7997,0.7474,class_weight

##### задание 3
Найдите модели, в названии которых встречается bert без учёта регистра. Используйте LOWER(model_name) и LIKE.

In [67]:
query = '''
SELECT DISTINCT model_name
FROM run_overview
WHERE
    LOWER(model_name) LIKE '%bert%';
'''
pd.read_sql_query(query, connection)

         model_name
0        DistilBERT
1  DeBERTa-v3-small
2      RuBERT-tiny2
3         BERT-base
4      RoBERTa-base

##### задание 4
Найдите завершённые запуски только для задач NLP или CV, где f1_score >= 0.80.

In [68]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    f1_score >= 0.80
    AND
    task_type IN ('NLP', 'CV');
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,1,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,RTX 4090,2026-08-31 15:51:00,38,0.00300,64,0.8618,0.8688,debug
1,4,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,T4,2026-09-04 08:19:00,127,0.00030,64,0.8055,0.8287,full_train
2,7,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-28 09:10:00,195,0.00100,32,0.9198,0.8749,debug
3,9,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,CPU,2026-09-01 09:38:00,66,0.01000,32,0.8899,0.9042,fast_test
4,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
5,13,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-16 09:13:00,67,0.00010,16,0.9406,0.9577,tuned
6,14,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,L40S,2026-09-17 17:04:00,233,0.00010,16,0.8477,0.8500,debug
7,16,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,T4,2026-08-30 09:12:00,184,0.00100,64,0.9850,0.9800,full_train
8,18,18,cv_new_features_018,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,RTX 4090,2026-08-24 14:27:00,69,0.01000,64,0.8670,0.8915,tuned
9,20,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,CPU,2026-09-28 09:32:00,241,0.01000,64,0.9340,0.8968,production_candidate
10,22,22,nlp_class_weight_022,Иван Ким,NLP,DeBERTa-v3-small,DeBERTa,NLP,RuSentiment,internal,31000,completed,T4,2026-09-18 18:51:00,130,0.00010,16,0.9291,0.9301,tuned
11,27,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,RTX 4090,2026-08-29 15:47:00,135,0.00300,32,0.9226,0.8859,production_candidate
12,28,28,cv_lr_sweep_028,Алексей Пак,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,T4,2026-09-09 07:55:00,276,0.00030,64,0.9403,0.9514,full_train
13,32,32,cv_baseline_032,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,H100,2026-09-07 09:47:00,127,0.00005,16,0.8400,0.8091,augmentation
14,39,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,T4,2026-09-23 17:21:00,149,0.01000,32,0.8938,0.9127,fast_test
15,43,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-08-24 07:34:00,208,0.00010,64,0.8797,0.8213,class_weight
16,45,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,A100,2026-09-15 15:27:00,212,0.00030,128,0.9022,0.8988,production_candidate
17,46,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,RTX 4090,2026-08-29 17:16:00,59,0.00010,64,0.8922,0.8334,baseline
18,51,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,completed,T4,2026-09-04 16:37:00,228,0.00030,64,0.9587,0.9498,class_weight
19,52,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,A100,2026-08-30 03:36:00,257,0.00100,32,0.8795,0.8905,production_candidate
20,57,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,CPU,2026-08-23 05:08:00,9,0.00010,128,0.8668,0.8610,production_candidate
21,58,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,RTX 4090,2026-09-18 11:48:00,73,0.00300,64,0.9412,0.9510,tuned
22,59,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,T4,2026-09-19 16:06:00,199,0.00010,32,0.9850,0.9695,fast_test
23,60,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-08-28 09:45:00,66,0.01000,16,0.8903,0.8975,production_candidate
24,61,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-29 18:01:00,174,0.00010,16,0.9750,0.9697,class_weight
25,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
26,68,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,RTX 4090,2026-09-05 05:09:00,163,0.00030,128,0.8410,0.8127,production_candidate
27,72,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-08-28 12:42:00,216,0.00030,32,0.9300,0.8911,baseline
28,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.01000,128,0.9061,0.8563,class_weight
29,77,32,cv_baseline_032,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,L40S,2026-09-07 05:45:00,184,0.00030,128,0.8698,0.8467,debug
30,79,34,nlp_sanity_check_034,Максим Чернов,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,L40S,2026-09-03 08:28:00,112,0.00030,16,0.9388,0.8891,augmentation
31,82,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,completed,RTX 4090,2026-08-20 14:27:00,114,0.00010,64,0.8521,0.8274,full_train
32,84,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,L40S,2026-09-20 21:58:00,234,0.01000,64,0.8972,0.9012,baseline
33,96,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,completed,T4,2026-09-07 14:48:00,119,0.01000,128,0.8801,0.8857,baseline
34,97,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,H100,2026-08-28 23:44:00,96,0.01000,32,0.8206,0.8271,augmentation
35,98,8,cv_tuned_008,Дарья Новикова,CV,ResNet50,ResNet,CV,CIFAR-10,public,60000,completed,L40S,2026-09-01 09:07:00,201,0.00030,16,0.8307,0.8086,debug
36,100,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,completed,L40S,2026-09-17 18:05:00,38,0.00300,32,0.8901,0.8604,baseline
37,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
38,104,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-17 12:27:00,198,0.00010,16,0.8879,0.8348,tuned
39,105,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,L40S,2026-08-27 21:43:00,180,0.00030,64,0.9503,0.9256,augmentation
40,106,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,CPU,2026-08-27 11:34:00,264,0.00010,16,0.8314,0.8099,full_train
41,119,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,H100,2026-09-17 13:32:00,182,0.01000,128,0.9240,0.9325,fast_test
42,122,32,cv_baseline_032,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,completed,CPU,2026-09-06 02:59:00,257,0.00030,128,0.8297,0.8276,class_weight
43,127,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,completed,A100,2026-08-21 05:51:00,194,0.00030,128,0.8636,0.8130,augmentation
44,129,39,cv_tuned_039,Анна Волкова,CV,ResNet50,ResNet,CV,Cats vs Dogs,public,25000,completed,H100,2026-09-23 20:51:00,124,0.01000,32,0.9518,0.9502,tuned
45,137,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-01 10:27:00,78,0.00100,64,0.8903,0.8368,baseline
46,141,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,completed,RTX 4090,2026-09-05 05:04:00,61,0.00005,64,0.8535,0.8105,class_weight
47,142,7,nlp_augmentation_007,Ольга Белова,NLP,DeBERTa-v3-small,DeBERTa,NLP,IMDB Reviews,public,50000,completed,L40S,2026-08-29 02:37:00,271,0.00010,32,0.9415,0.8897,debug
48,144,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-01 05:32:00,77,0.00030,64,0.9109,0.8770,baseline
49,146,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,completed,L40S,2026-08-28 22:11:00,238,0.00010,16,0.9590,0.9475,debug
50,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
51,149,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,H100,2026-09-16 12:07:00,154,0.00100,128,0.8619,0.8500,tuned
52,150,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,70000,completed,RTX 4090,2026-08-28 15:05:00,106,0.00010,128,0.8319,0.8462,tuned
53,151,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,RTX 4090,2026-08-27 10:24:00,23,0.00005,16,0.9255,0.8660,full_train
54,158,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,completed,A100,2026-09-06 01:54:00,52,0.00005,128,0.9058,0.8876,debug
55,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.00010,32,0.9721,0.9654,production_candidate

##### задание 5
Найдите 10 самых долгих запусков. Выведите model_name, dataset_name, task_type, gpu, duration_min.

In [69]:
query = '''
SELECT model_name, dataset_name, task_type, gpu, duration_min
FROM run_overview
ORDER BY duration_min DESC
LIMIT 10;
'''
pd.read_sql_query(query, connection)

         model_name     dataset_name task_type       gpu  duration_min
0          LightGBM   Credit Default   Tabular        T4           279
1          LightGBM   Customer Churn   Tabular      A100           278
2          ResNet50     PlantVillage        CV        T4           276
3  DeBERTa-v3-small     IMDB Reviews       NLP      L40S           271
4           XGBoost  Student Success   Tabular        T4           268
5      RandomForest  Student Success   Tabular      L40S           264
6        DistilBERT     IMDB Reviews       NLP       CPU           264
7          CatBoost  Student Success   Tabular  RTX 4090           263
8           XGBoost  Student Success   Tabular      A100           258
9  DeBERTa-v3-small     IMDB Reviews       NLP      A100           257

##### задание 6
Найдите завершённые A100/H100-запуски с f1_score < 0.75. Выведите модель, датасет, GPU, длительность и F1.

In [70]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = 'completed'
    AND
    gpu IN ('A100', 'H100')
    AND
    f1_score < 0.75;
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,17,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-04 08:35:00,59,0.0100,128,0.7296,0.7422,class_weight
1,25,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 11:00:00,198,0.0010,64,0.7210,0.6940,baseline
2,47,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-02 16:34:00,10,0.0010,128,0.7452,0.7328,class_weight
3,49,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-04 03:34:00,72,0.0010,128,0.6711,0.6258,debug
4,78,33,tabular_lr_sweep_033,Даниил Ли,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,H100,2026-09-15 15:20:00,231,0.0030,32,0.7480,0.7120,debug
5,109,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-12 02:39:00,125,0.0003,128,0.7893,0.7389,debug
6,139,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,completed,A100,2026-09-03 01:42:00,134,0.0100,16,0.7451,0.7006,debug

##### задание 7
Найдите 10 завершённых запусков, где accuracy сильнее всего превышает f1_score. Добавьте вычисляемый столбец metric_gap = accuracy - f1_score и отсортируйте по убыванию.

In [71]:
query = '''
SELECT *, accuracy - f1_score AS metric_gap
FROM run_overview 
ORDER BY metric_gap DESC
LIMIT 10;
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,...,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes,metric_gap
0,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,...,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate,0.0596
1,151,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,...,completed,RTX 4090,2026-08-27 10:24:00,23,0.00005,16,0.9255,0.8660,full_train,0.0595
2,70,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,...,completed,L40S,2026-09-21 17:48:00,127,0.00100,16,0.9452,0.8863,class_weight,0.0589
3,46,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,...,completed,RTX 4090,2026-08-29 17:16:00,59,0.00010,64,0.8922,0.8334,baseline,0.0588
4,43,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,...,completed,A100,2026-08-24 07:34:00,208,0.00010,64,0.8797,0.8213,class_weight,0.0584
5,83,38,tabular_baseline_038,Даниил Ли,Tabular,LightGBM,Gradient Boosting,Tabular,Credit Default,public,...,completed,T4,2026-09-24 11:17:00,279,0.01000,16,0.8205,0.7627,production_candidate,0.0578
6,30,30,tabular_dropout_030,Никита Фролов,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,...,completed,RTX 4090,2026-09-24 13:50:00,186,0.00005,128,0.7616,0.7043,baseline,0.0573
7,50,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,...,completed,H100,2026-08-31 07:04:00,50,0.00300,16,0.8237,0.7683,debug,0.0554
8,15,15,cv_sanity_check_015,Софья Миронова,CV,EfficientNet-B0,EfficientNet,CV,Fashion-MNIST,public,...,completed,T4,2026-08-26 16:04:00,40,0.00300,64,0.7947,0.7395,fast_test,0.0552
9,137,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,...,completed,A100,2026-09-01 10:27:00,78,0.00100,64,0.8903,0.8368,baseline,0.0535

##### задание 8
Найдите запуски на внутренних датасетах (dataset_source = 'internal'), выполненные не на CPU, с accuracy >= 0.85.

In [72]:
query = '''
SELECT *
FROM run_overview 
WHERE
    dataset_source = 'internal'
    AND
    NOT gpu = 'CPU'
    AND
    accuracy >= 0.85;
'''
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,1,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,RTX 4090,2026-08-31 15:51:00,38,0.00300,64,0.8618,0.8688,debug
1,3,3,tabular_class_weight_003,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Fraud Mini,internal,125000,completed,RTX 4090,2026-09-13 23:14:00,191,0.00010,128,0.8547,0.8013,full_train
2,5,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-08-28 16:46:00,129,0.00010,64,0.9473,0.9254,full_train
3,12,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-25 02:29:00,112,0.00010,16,0.8816,0.9066,fast_test
4,22,22,nlp_class_weight_022,Иван Ким,NLP,DeBERTa-v3-small,DeBERTa,NLP,RuSentiment,internal,31000,completed,T4,2026-09-18 18:51:00,130,0.00010,16,0.9291,0.9301,tuned
5,24,24,tabular_tuned_024,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Student Success,internal,18000,completed,L40S,2026-08-29 16:19:00,264,0.00030,128,0.8810,0.8698,baseline
6,26,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 22:02:00,189,0.00010,32,0.8745,0.8376,augmentation
7,35,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,A100,2026-09-10 07:48:00,204,0.00100,32,0.8785,0.8335,production_candidate
8,46,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,RTX 4090,2026-08-29 17:16:00,59,0.00010,64,0.8922,0.8334,baseline
9,51,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,completed,T4,2026-09-04 16:37:00,228,0.00030,64,0.9587,0.9498,class_weight
10,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.01000,64,0.9291,0.8695,production_candidate
11,66,21,tabular_tuned_021,Даниил Ли,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,T4,2026-09-16 10:11:00,249,0.00100,64,0.9254,0.9113,production_candidate
12,70,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,L40S,2026-09-21 17:48:00,127,0.00100,16,0.9452,0.8863,class_weight
13,71,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-19 18:46:00,278,0.00005,32,0.9046,0.9282,augmentation
14,80,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-09 21:42:00,137,0.01000,128,0.8894,0.8389,production_candidate
15,93,3,tabular_class_weight_003,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Fraud Mini,internal,125000,completed,T4,2026-09-10 20:48:00,213,0.00100,16,0.9024,0.8694,full_train
16,95,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,completed,A100,2026-09-01 10:21:00,224,0.00030,16,0.8767,0.8807,full_train
17,96,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,completed,T4,2026-09-07 14:48:00,119,0.01000,128,0.8801,0.8857,baseline
18,100,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,completed,L40S,2026-09-17 18:05:00,38,0.00300,32,0.8901,0.8604,baseline
19,102,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,A100,2026-08-22 14:04:00,42,0.00300,128,0.9582,0.9481,class_weight
20,114,24,tabular_tuned_024,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Student Success,internal,18000,completed,T4,2026-08-27 10:11:00,167,0.00005,16,0.9290,0.8854,debug
21,126,36,tabular_sanity_check_036,Мария Орлова,Tabular,LogisticRegression,Linear,Tabular,Fraud Mini,internal,125000,completed,T4,2026-09-25 02:51:00,162,0.00100,128,0.9637,0.9614,debug
22,131,41,tabular_lr_sweep_041,Полина Кравцова,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,RTX 4090,2026-09-14 04:34:00,189,0.00300,64,0.8516,0.8672,full_train
23,134,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,H100,2026-09-15 21:08:00,148,0.01000,32,0.8723,0.8665,tuned
24,141,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,completed,RTX 4090,2026-09-05 05:04:00,61,0.00005,64,0.8535,0.8105,class_weight
25,146,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,completed,L40S,2026-08-28 22:11:00,238,0.00010,16,0.9590,0.9475,debug
26,147,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,H100,2026-08-26 11:57:00,101,0.00010,64,0.9588,0.9428,full_train
27,152,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,H100,2026-09-04 14:03:00,213,0.01000,64,0.8727,0.8727,production_candidate

### Выводы по данным

##### вопрос 1
По заданию 6 напишите 1–2 предложения: что можно утверждать по результату запроса, а что нельзя доказать только этими данными?

выборка произведена по фильтру определающему видеокарты и результат вычислений \
по этим критериям мы не можем делать никаких выводов. кроме факта наличия результатов по такому запросу \
то есть эти 2 GPU не гарантируют хороших результатов \
\
Мы бы могли распространить это суждение на все видеокарты (по логическим причинам), но такая выборка нам не даёт никакого представления о генеральной выборке

##### вопрос 2
Выберите любой один свой запрос из второй пары и напишите короткий аналитический вывод: не про SQL, а про данные.

возьму задание 5 \
можно проверить гипотезу о малой мощности видеокарты T4 или о том, что модель LightGBM очень медленная

### вывод 2 пары

1. На A100 и H100 есть завершённые запуски с f1_score < 0.75 (Fraud Mini, Cats vs Dogs, Credit Default) — GPU (A100 и H100) не гарантируют высокое качество модели.
2. Самые долгие запуски идут по 250+ минут не только на T4, но и на A100 (LightGBM, DeBERTa, XGBoost) — длительность сильнее зависит от модели и датасета, чем от типа видеокарты.

### Expert Track

##### EXPERT A
Аналитик пишет SELECT DISTINCT model_name, f1_score ... и ожидает по одной строке на модель. \
Получит ли он это? Объясните, к чему именно применяется DISTINCT,\
и предложите корректный запрос для списка уникальных моделей.

In [73]:
query = '''
SELECT model_name, f1_score 
FROM run_overview ;
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

           model_name  f1_score
0          DistilBERT    0.8688
1       ConvNeXt-Tiny    0.7586
2        RandomForest    0.8013
3         MobileNetV3    0.8287
4            LightGBM    0.9254
..                ...       ...
155      RandomForest       NaN
156  DeBERTa-v3-small       NaN
157          ResNet50    0.8876
158      RandomForest       NaN
159         BERT-base    0.9654

[160 rows x 2 columns]

In [74]:
query = '''
SELECT DISTINCT model_name, f1_score 
FROM run_overview ;
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

          model_name  f1_score
0         DistilBERT    0.8688
1      ConvNeXt-Tiny    0.7586
2       RandomForest    0.8013
3        MobileNetV3    0.8287
4           LightGBM    0.9254
..               ...       ...
122         CatBoost    0.8727
123  EfficientNet-B0       NaN
124          XGBoost    0.7474
125         ResNet50    0.8876
126        BERT-base    0.9654

[127 rows x 2 columns]

Distinct применяется ко всему списку выбранных полей и будет выводить только уникальные множества (a,b), \
то есть будет одна модель в нескольких строках из-за разных результатов \
я бы предложил использовать GROUP BY и агрегировать f1_score как среднее значение

In [75]:
query = '''
SELECT
    model_name,
    AVG(f1_score) AS f1_score
FROM run_overview
GROUP BY model_name;
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

            model_name  f1_score
0            BERT-base  0.925200
1             CatBoost  0.777800
2        ConvNeXt-Tiny  0.776067
3     DeBERTa-v3-small  0.854355
4           DistilBERT  0.880780
5      EfficientNet-B0  0.841264
6             LightGBM  0.822840
7   LogisticRegression  0.799929
8          MobileNetV3  0.744100
9         RandomForest  0.817042
10            ResNet50  0.872012
11        RoBERTa-base  0.914625
12        RuBERT-tiny2  0.748033
13             XGBoost  0.742660

##### EXPERT B
Найдите запуски, где отсутствует accuracy или f1_score. \
Если IS NULL вы ещё не проходили — документацией пользоваться можно. \
Какие статусы чаще встречаются у таких строк и почему пропуски важны для аналитика?

In [76]:
query = '''
SELECT *
FROM run_overview
WHERE
    accuracy IS NULL
    OR
    f1_score IS NULL
;
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,6,6,nlp_dropout_006,Максим Чернов,NLP,DeBERTa-v3-small,DeBERTa,NLP,Support Tickets RU,internal,82500,failed,T4,2026-09-04 21:23:00,17,0.00010,32,0.6171,NaN,production_candidate
1,10,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-09-18 07:21:00,225,0.00010,64,0.5504,NaN,augmentation
2,11,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-08-28 01:44:00,199,0.00005,64,NaN,NaN,baseline
3,19,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,cancelled,L40S,2026-09-11 21:23:00,247,0.00100,128,NaN,NaN,production_candidate
4,23,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,cancelled,H100,2026-09-06 06:09:00,108,0.00300,64,NaN,NaN,augmentation
5,29,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,cancelled,RTX 4090,2026-09-17 10:32:00,60,0.00100,128,0.6162,NaN,augmentation
6,31,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,failed,CPU,2026-09-24 19:57:00,207,0.00010,32,NaN,NaN,production_candidate
7,34,34,nlp_sanity_check_034,Максим Чернов,NLP,BERT-base,BERT,NLP,AG News,public,120000,failed,H100,2026-09-03 13:27:00,187,0.00030,16,NaN,NaN,production_candidate
8,36,36,tabular_sanity_check_036,Мария Орлова,Tabular,LogisticRegression,Linear,Tabular,Fraud Mini,internal,125000,failed,A100,2026-09-24 09:17:00,77,0.01000,16,NaN,NaN,class_weight
9,37,37,nlp_new_features_037,Роман Козлов,NLP,DeBERTa-v3-small,DeBERTa,NLP,AG News,public,120000,cancelled,A100,2026-08-22 23:02:00,101,0.00030,16,NaN,0.6992,full_train
10,53,8,cv_tuned_008,Дарья Новикова,CV,ResNet50,ResNet,CV,CIFAR-10,public,60000,running,L40S,2026-08-30 11:57:00,187,0.00300,32,NaN,NaN,debug
11,54,9,cv_new_features_009,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,failed,CPU,2026-08-29 17:22:00,143,0.00010,128,NaN,NaN,tuned
12,56,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,cancelled,CPU,2026-08-27 08:58:00,185,0.01000,16,0.6650,NaN,tuned
13,62,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,running,CPU,2026-09-05 14:23:00,127,0.01000,16,NaN,NaN,class_weight
14,64,19,tabular_augmentation_019,Мария Орлова,Tabular,XGBoost,Gradient Boosting,Tabular,Student Success,internal,18000,failed,H100,2026-09-14 05:17:00,94,0.00030,32,NaN,NaN,production_candidate
15,67,22,nlp_class_weight_022,Иван Ким,NLP,DeBERTa-v3-small,DeBERTa,NLP,RuSentiment,internal,31000,running,L40S,2026-09-20 19:36:00,133,0.00100,32,NaN,NaN,fast_test
16,73,28,cv_lr_sweep_028,Алексей Пак,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,failed,A100,2026-09-11 08:11:00,92,0.00300,16,NaN,NaN,production_candidate
17,74,29,nlp_lr_sweep_029,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,failed,A100,2026-09-18 11:17:00,200,0.00300,16,NaN,NaN,augmentation
18,86,41,tabular_lr_sweep_041,Полина Кравцова,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,running,CPU,2026-09-13 04:34:00,77,0.00030,16,NaN,0.6530,baseline
19,88,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,cancelled,L40S,2026-08-23 20:56:00,252,0.00005,16,NaN,NaN,production_candidate
20,90,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,cancelled,A100,2026-09-18 10:12:00,166,0.00030,16,NaN,NaN,production_candidate
21,91,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,failed,T4,2026-08-29 21:26:00,64,0.00300,128,0.6610,NaN,debug
22,92,2,cv_sanity_check_002,Артём Юн,CV,ConvNeXt-Tiny,ConvNeXt,CV,Cats vs Dogs,public,25000,running,T4,2026-09-03 18:07:00,14,0.00030,32,0.7359,NaN,full_train
23,94,4,cv_new_features_004,Софья Миронова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,cancelled,CPU,2026-09-04 04:37:00,174,0.00005,64,NaN,NaN,baseline
24,101,11,nlp_augmentation_011,Иван Ким,NLP,BERT-base,BERT,NLP,Support Tickets RU,internal,82500,cancelled,L40S,2026-08-27 10:23:00,118,0.00005,32,NaN,NaN,production_candidate
25,103,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,running,A100,2026-09-19 13:27:00,174,0.00100,64,NaN,NaN,augmentation
26,107,17,tabular_baseline_017,Полина Кравцова,Tabular,CatBoost,Gradient Boosting,Tabular,Fraud Mini,internal,125000,running,RTX 4090,2026-09-05 09:59:00,246,0.00100,128,NaN,0.5307,baseline
27,110,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,failed,RTX 4090,2026-09-25 19:44:00,200,0.00010,128,NaN,NaN,class_weight
28,112,22,nlp_class_weight_022,Иван Ким,NLP,DeBERTa-v3-small,DeBERTa,NLP,RuSentiment,internal,31000,running,L40S,2026-09-20 15:51:00,194,0.01000,128,NaN,NaN,production_candidate
29,113,23,cv_dropout_023,Артём Юн,CV,ResNet50,ResNet,CV,PlantVillage,public,54303,cancelled,T4,2026-09-08 06:43:00,134,0.01000,128,NaN,NaN,class_weight
30,115,25,tabular_lr_sweep_025,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,cancelled,H100,2026-09-25 06:37:00,88,0.00100,64,NaN,NaN,tuned
31,116,26,tabular_dropout_026,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,cancelled,A100,2026-09-20 11:47:00,181,0.00100,16,NaN,NaN,debug
32,117,27,cv_baseline_027,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,running,H100,2026-08-30 03:22:00,77,0.00010,128,0.6632,NaN,production_candidate
33,121,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,failed,T4,2026-09-26 20:42:00,175,0.00030,128,NaN,NaN,full_train
34,124,34,nlp_sanity_check_034,Максим Чернов,NLP,BERT-base,BERT,NLP,AG News,public,120000,failed,H100,2026-09-06 01:27:00,151,0.00100,16,NaN,NaN,full_train
35,125,35,tabular_dropout_035,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,cancelled,L40S,2026-09-10 16:49:00,28,0.00300,128,NaN,NaN,production_candidate
36,130,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,cancelled,A100,2026-09-02 11:11:00,71,0.00100,32,NaN,0.7857,class_weight
37,132,42,tabular_sanity_check_042,Мария Орлова,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,running,A100,2026-09-13 13:13:00,243,0.00010,64,NaN,NaN,fast_test
38,133,43,cv_baseline_043,Анна Волкова,CV,MobileNetV3,MobileNet,CV,Cats vs Dogs,public,25000,failed,H100,2026-08-25 06:58:00,9,0.00005,64,0.6604,NaN,debug
39,135,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,running,RTX 4090,2026-09-17 09:17:00,31,0.00005,64,NaN,NaN,tuned
40,138,3,tabular_class_weight_003,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Fraud Mini,internal,125000,failed,L40S,2026-09-14 01:20:00,214,0.00300,32,NaN,NaN,tuned
41,140,5,tabular_baseline_005,Никита Фролов,Tabular,LightGBM,Gradient Boosting,Tabular,Customer Churn,internal,10000,failed,A100,2026-08-31 22:56:00,50,0.00005,32,NaN,NaN,baseline
42,143,8,cv_tuned_008,Дарья Новикова,CV,ResNet50,ResNet,CV,CIFAR-10,public,60000,failed,H100,2026-08-29 13:20:00,73,0.00030,16,0.6308,NaN,tuned
43,145,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,failed,L40S,2026-09-19 15:42:00,53,0.00300,32,NaN,0.6021,full_train
44,148,13,cv_tuned_013,Софья Миронова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,running,T4,2026-09-18 00:24:00,244,0.01000,64,0.8191,NaN,full_train
45,153,18,cv_new_features_018,Алексей Пак,CV,EfficientNet-B0,EfficientNet,CV,CIFAR-10,public,60000,failed,RTX 4090,2026-08-23 10:24:00,51,0.00010,16,NaN,NaN,augmentation
46,155,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,failed,H100,2026-09-24 09:37:00,28,0.00010,64,NaN,NaN,debug
47,156,21,tabular_tuned_021,Даниил Ли,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,failed,A100,2026-09-14 13:14:00,234,0.00010,128,NaN,NaN,tuned
48,157,22,nlp_class_weight_022,Иван Ким,NLP,DeBERTa-v3-small,DeBERTa,NLP,RuSentiment,internal,31000,running,A100,2026-09-18 12:31:00,133,0.00030,64,NaN,NaN,production_candidate
49,159,24,tabular_tuned_024,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Student Success,internal,18000,running,A100,2026-08-27 12:57:00,248,0.00100,32,NaN,NaN,baseline

In [77]:
query = '''
SELECT DISTINCT status
FROM run_overview;
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

      status
0  completed
1     failed
2  cancelled
3    running

In [78]:
query = '''
SELECT
    SUM(status = "failed") AS failed,
    SUM(status = "running") AS running,
    SUM(status = "cancelled") AS cancelled,
    SUM(status = "completed") AS completed
FROM run_overview
WHERE
    accuracy IS NULL
    OR
    f1_score IS NULL
;
'''
pd.read_sql_query(query, connection)

   failed  running  cancelled  completed
0      22       14         14          0

эти данные важны для аналитика, так как такие записи либо удалят, либо попытаются восстановить на основе других значений, что может испортить результат

##### EXPERT C
Если базовый SQL для вас слишком прост: получите по одному лучшему запуску для каждого task_type. \
Можно использовать любые знакомые вам средства SQL. Объясните решение преподавателю — это задание специально выходит вперёд лекции.

In [79]:
query = '''
SELECT 
    sample.task_type,
    sample.accuracy,
    run_id,
    experiment_id,
    experiment_title,
    researcher_name,
    researcher_team, 
    model_name,
    model_family,
    dataset_name,
    dataset_source,
    dataset_records,
    status,
    gpu,
    started_at,
    duration_min,
    learning_rate,
    batch_size,
    f1_score,
    notes

FROM 
    (
        SELECT task_type, MAX(accuracy) as accuracy
        FROM run_overview
        GROUP BY task_type
    ) sample
    INNER JOIN
    run_overview full_tabel
    ON
        sample.task_type == full_tabel.task_type
        AND
        sample.accuracy == full_tabel.accuracy
;
'''
pd.read_sql_query(query, connection)

,task_type,accuracy,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,f1_score,notes
0,CV,0.9850,59,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,Fashion-MNIST,public,70000,completed,T4,2026-09-19 16:06:00,199,0.0001,32,0.9695,fast_test
1,NLP,0.9850,16,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,IMDB Reviews,public,50000,completed,T4,2026-08-30 09:12:00,184,0.0010,64,0.9800,full_train
2,Tabular,0.9637,126,36,tabular_sanity_check_036,Мария Орлова,Tabular,LogisticRegression,Linear,Fraud Mini,internal,125000,completed,T4,2026-09-25 02:51:00,162,0.0010,128,0.9614,debug

In [80]:
query = '''
SELECT *
FROM 
    (
        SELECT task_type, MAX(accuracy) as accuracy
        FROM run_overview
        GROUP BY task_type
    ) sample
    INNER JOIN
    run_overview full_tabel
    USING(task_type, accuracy);
'''
pd.read_sql_query(query, connection)

,task_type,accuracy,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,f1_score,notes
0,CV,0.9850,59,14,cv_augmentation_014,Алексей Пак,CV,EfficientNet-B0,EfficientNet,Fashion-MNIST,public,70000,completed,T4,2026-09-19 16:06:00,199,0.0001,32,0.9695,fast_test
1,NLP,0.9850,16,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,IMDB Reviews,public,50000,completed,T4,2026-08-30 09:12:00,184,0.0010,64,0.9800,full_train
2,Tabular,0.9637,126,36,tabular_sanity_check_036,Мария Орлова,Tabular,LogisticRegression,Linear,Fraud Mini,internal,125000,completed,T4,2026-09-25 02:51:00,162,0.0010,128,0.9614,debug

### Семестровый проект

1) я собираюсь сделать систему обработки персонажей видеоигры (сами игроки, NPC, монстры, боссы, иные существа)
2) системой будет пользоваться игровой движок или аналитики (для улучшения баланса игры или отслеживание ошибок игры)
3) решает проблемы:
    - сложность дебага чёрной ящика
    - нет возможности подключать аналитиков к данным игры 
    - сложность игрового движка 1 (чтобы игровой движок не был перегружен задачами хранения данных)
    - сложность игрового движка 2 (если будет иметь серьёзный смысл, сделать такое через макросы и тригеры) (просчёт здоровья, опыта, силы, маны в боях в базе данных, а не в движке)
4) игра/сессия, персонаж, типы_персонажей, локации, их_оружие_и_предметы, журнал_логов
5) пять содержательных вопросов, на которые будущая система должна уметь отвечать с помощью данных:
    аналитика:
    - самые лучшие игроки в плане скила
    - самые смертоносные боссы игры
    - самые часто используемые предметы
    - как хорошо разрекламировано игра: много ли у нас "постоянников"
    - токсичные игроки
    игровой движок:
    - состояние чего-либо для прорисовки и просчёта
    - статистика сессии
    - (возможно) игрок 1 нанёс урон существу 253, посчитай урон нанесённый, здоровье существа, изношенность предмета, состояние брони, маны

### Домашняя работа

##### задание 1
Найдите 5 самых свежих завершённых запусков.

In [81]:
query = '''
SELECT *
FROM run_overview
WHERE
    status = "completed"
ORDER BY started_at DESC
LIMIT 5;
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,20,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,CPU,2026-09-28 09:32:00,241,0.0100,64,0.9340,0.8968,production_candidate
1,65,20,nlp_new_features_020,Максим Чернов,NLP,DistilBERT,BERT,NLP,Support Tickets RU,internal,82500,completed,A100,2026-09-27 07:01:00,111,0.0100,64,0.9291,0.8695,production_candidate
2,160,45,nlp_tuned_045,Иван Ким,NLP,BERT-base,BERT,NLP,AG News,public,120000,completed,H100,2026-09-25 12:30:00,74,0.0001,32,0.9721,0.9654,production_candidate
3,76,31,cv_dropout_031,Анна Волкова,CV,ResNet50,ResNet,CV,Fashion-MNIST,public,70000,completed,A100,2026-09-25 05:13:00,58,0.0100,128,0.9061,0.8563,class_weight
4,126,36,tabular_sanity_check_036,Мария Орлова,Tabular,LogisticRegression,Linear,Tabular,Fraud Mini,internal,125000,completed,T4,2026-09-25 02:51:00,162,0.0010,128,0.9637,0.9614,debug

##### задание 2

In [82]:
query = '''
SELECT model_name, dataset_name, accuracy, started_at
FROM run_overview
WHERE
    gpu = "A100"
    AND
    accuracy >= 0.90;
'''
pd.read_sql_query(query, connection)

     model_name        dataset_name  accuracy           started_at
0      LightGBM      Customer Churn    0.9473  2026-08-28 16:46:00
1      ResNet50       Fashion-MNIST    0.9406  2026-09-16 09:13:00
2     BERT-base             AG News    0.9022  2026-09-15 15:27:00
3    DistilBERT  Support Tickets RU    0.9291  2026-09-27 07:01:00
4      LightGBM      Customer Churn    0.9046  2026-09-19 18:46:00
5      ResNet50       Fashion-MNIST    0.9300  2026-08-28 12:42:00
6      ResNet50       Fashion-MNIST    0.9061  2026-09-25 05:13:00
7  RoBERTa-base  Support Tickets RU    0.9582  2026-08-22 14:04:00
8      ResNet50        PlantVillage    0.9058  2026-09-06 01:54:00

##### задание 3

In [83]:
query = '''
SELECT *
FROM run_overview
WHERE
    accuracy >= 0.80
    AND
    status = "completed"
ORDER BY duration_min
LIMIT 10;
'''
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(pd.read_sql_query(query, connection))
pd.read_sql_query(query, connection)

,run_id,experiment_id,experiment_title,researcher_name,researcher_team,model_name,model_family,task_type,dataset_name,dataset_source,dataset_records,status,gpu,started_at,duration_min,learning_rate,batch_size,accuracy,f1_score,notes
0,57,12,nlp_class_weight_012,Ольга Белова,NLP,RoBERTa-base,RoBERTa,NLP,Support Tickets RU,internal,82500,completed,CPU,2026-08-23 05:08:00,9,0.00010,128,0.8668,0.8610,production_candidate
1,151,16,nlp_dropout_016,Иван Ким,NLP,DistilBERT,BERT,NLP,IMDB Reviews,public,50000,completed,RTX 4090,2026-08-27 10:24:00,23,0.00005,16,0.9255,0.8660,full_train
2,41,41,tabular_lr_sweep_041,Полина Кравцова,Tabular,LightGBM,Gradient Boosting,Tabular,Fraud Mini,internal,125000,completed,T4,2026-09-12 14:38:00,25,0.00100,128,0.8415,0.7960,augmentation
3,89,44,tabular_dropout_044,Даниил Ли,Tabular,CatBoost,Gradient Boosting,Tabular,Student Success,internal,18000,completed,T4,2026-09-16 03:49:00,30,0.00300,64,0.8064,0.8085,baseline
4,69,24,tabular_tuned_024,Мария Орлова,Tabular,RandomForest,Tree Ensemble,Tabular,Student Success,internal,18000,completed,RTX 4090,2026-08-30 10:44:00,37,0.00030,128,0.8406,0.8204,tuned
5,1,1,nlp_tuned_001,Максим Чернов,NLP,DistilBERT,BERT,NLP,RuSentiment,internal,31000,completed,RTX 4090,2026-08-31 15:51:00,38,0.00300,64,0.8618,0.8688,debug
6,100,10,nlp_new_features_010,Максим Чернов,NLP,RuBERT-tiny2,BERT,NLP,Support Tickets RU,internal,82500,completed,L40S,2026-09-17 18:05:00,38,0.00300,32,0.8901,0.8604,baseline
7,40,40,tabular_new_features_040,Никита Фролов,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,H100,2026-08-31 20:26:00,40,0.01000,128,0.8067,0.7747,augmentation
8,87,42,tabular_sanity_check_042,Мария Орлова,Tabular,LogisticRegression,Linear,Tabular,Credit Default,public,30000,completed,L40S,2026-09-12 07:50:00,40,0.00100,128,0.8795,0.8436,class_weight
9,111,21,tabular_tuned_021,Даниил Ли,Tabular,RandomForest,Tree Ensemble,Tabular,Customer Churn,internal,10000,completed,T4,2026-09-15 12:06:00,40,0.00100,64,0.8211,0.7703,augmentation

### Необязательное Expert homework

Исследуйте, как ведёт себя NOT IN, если в наборе сравнения появляется NULL. \
Сделайте минимальный пример и объясните результат своими словами.

по примеру ниже видим, что проверка на наличи в множестве ведёт себя странно

In [84]:
query = '''
SELECT (1 IS NULL), (1 IS NOT NULL), (1 NOT IN (2, NULL))
;
'''
pd.read_sql_query(query, connection)

   (1 IS NULL)  (1 IS NOT NULL) (1 NOT IN (2, NULL))
0            0                1                 None

проверку мы можем выразить в другом виде, то есть \
a NOT IN (b, NULL)   =>    a <> b AND a <> NULL \
и как раз эта часть (a <> NULL) и даёт None, \
потому что NULL - это отсутствие присутствия, а не присутстыие отсутствия (0)
поэтому необходимо использовать проверку на нулы и синтаксис IS NOT NULL

In [85]:
query = '''
SELECT (1 <> NULL), (1 IS NOT NULL), (1 NOT IN (2, NULL))
;
'''
pd.read_sql_query(query, connection)

  (1 <> NULL)  (1 IS NOT NULL) (1 NOT IN (2, NULL))
0        None                1                 None

# --

In [86]:
connection.close()