In [1]:
import pandas as pd
from pprint import pprint

In [2]:
MAIN_FOLDER = "/home/arman/it/AI_work/analyze_data/perfume"

In [3]:
data = pd.read_csv(f"{MAIN_FOLDER}/dataset/perfume.csv")
print(data.shape)
data.head()

(2000, 11)

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,is_man
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States",True
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada",True
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States",True
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States",True
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States",True

In [4]:
full_duplicates = data[data.duplicated(keep=False)]
print(f"Количество полных дубликатов: {full_duplicates.shape[0]}")
print(data.shape)
full_duplicates.head()

Количество полных дубликатов: 2
(2000, 11)

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,is_man
1344,FLOWER,12 Piece Woman’s Perfume Lot: Assorted scents ...,Perfume,48.0,US $48.00,4.0,4 available / 1 sold,1.0,NaN,"Webster, Florida, United States",False
1662,FLOWER,12 Piece Woman’s Perfume Lot: Assorted scents ...,Perfume,48.0,US $48.00,4.0,4 available / 1 sold,1.0,NaN,"Webster, Florida, United States",False

In [5]:
data = data[data.duplicated(keep="first") == False]  # noqa: E712
print(data.shape)
data.head()

(1999, 11)

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,is_man
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States",True
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada",True
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States",True
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States",True
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States",True

In [6]:
text_cols = ["brand", "title", "type", "itemLocation", "priceWithCurrency", "availableText"]
for col in text_cols:
    data[col] = data[col].astype("string").str.strip()

if data["is_man"].dtype != "bool":
    data["is_man"] = data["is_man"].astype(str).str.strip().str.lower().map({"true": True, "false": False})

for col in ["price", "available", "sold"]:
    data[col] = pd.to_numeric(data[col], errors="coerce")

data["title"] = data["title"].str.replace(r"\s+", " ", regex=True)

data.head()

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,is_man
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States",True
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada",True
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States",True
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States",True
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States",True

In [7]:
country_map = {
    "usa": "United States",
    "u.s.a": "United States",
    "us": "United States",
    "united states": "United States",
    "hongkong": "Hong Kong",
    "hong kong": "Hong Kong",
}

country_raw = data["itemLocation"].astype("string").str.split(",").str[-1].str.strip().str.lower()

data["country"] = country_raw.replace(country_map)
data["country"] = data["country"].str.title()

print(data["country"].value_counts())
data[["itemLocation", "country"]].head()

country
United States     1833
Hong Kong          100
China               25
Canada              16
Taiwan              12
India                4
Poland               2
Israel               1
Brazil               1
Portugal             1
Japan                1
Estados Unidos       1
Pakistan             1
Bulgaria             1
Name: count, dtype: int64

                             itemLocation        country
0     Allen Park, Michigan, United States  United States
1                Atlanta, Georgia, Canada         Canada
2       Dearborn, Michigan, United States  United States
3  Reinholds, Pennsylvania, United States  United States
4       Brooklyn, New York, United States  United States

In [8]:
data.to_csv(f"{MAIN_FOLDER}/dataset/cleaned_perfume.csv", index=False)